import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsDurableExternalVideoReferenceTableAttributes, TrailsDurableExternalVideoReferenceTable } from 'db/mysql/models/trailsDurableExternalVideoReference';
import { ITrailsDurableExternalVideoReferenceMutationTableAttributes, TrailsDurableExternalVideoReferenceMutationTable } from 'db/mysql/models/trailsDurableExternalVideoReferenceMutation';
import { ITrailsDurableExternalVideoReferenceAuditTableAttributes, TrailsDurableExternalVideoReferenceAuditTable } from 'db/mysql/models/trailsDurableExternalVideoReferenceAudit';
import { Actor, DurableExternalVideoReference, DurableExternalVideoReferenceDraftInput, DurableExternalVideoReferenceMutation, DurableExternalVideoReferenceStatus, DurableExternalVideoReferenceStore } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type Row = Omit<ITrailsDurableExternalVideoReferenceTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type Options = { transaction: TrailsSyncTransaction };
type Portfolio = { ownerUserId: string; visibility: string; lifecycle: string };
const safeText = (value: unknown, label: string, max: number) => { if (typeof value !== 'string') throw new TrailsSyncInputError(`${label}无效`); const result = value.trim(); if (!result || result.length > max || /[<>]|[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(result)) throw new TrailsSyncInputError(`${label}无效`); return result; };
const opaque = (value: unknown, label: string) => { const result = safeText(value, label, 160); if (!/^[A-Za-z0-9_-]+$/.test(result)) throw new TrailsSyncInputError(`${label}必须是安全不透明标识`); return result; };
const decimal = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError(`${label}必须是规范十进制字符串`); return value; };
const version = (value: unknown) => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : typeof value === 'number' && Number.isSafeInteger(value) ? String(value) : typeof value === 'bigint' ? value.toString() : (() => { throw new TrailsSyncPersistenceError('外部视频引用版本无效'); })();
const canonicalUrl = (value: unknown) => { if (typeof value !== 'string' || value.length > 256 || value !== value.trim()) throw new TrailsSyncInputError('canonicalUrl必须是规范Bilibili视频URL'); const match = /^https:\/\/www\.bilibili\.com\/video\/(BV[1-9A-HJ-NP-Za-km-z]{10})$/.exec(value); if (!match) throw new TrailsSyncInputError('canonicalUrl必须是规范Bilibili视频URL'); const canonical = `https://www.bilibili.com/video/${match[1]}`; if (value !== canonical) throw new TrailsSyncInputError('canonicalUrl必须是规范Bilibili视频URL'); return canonical; };
const payload = (value: Record<string, unknown>): DurableExternalVideoReferenceDraftInput => { const sortOrder = value.sortOrder; if (!Number.isSafeInteger(sortOrder) || (sortOrder as number) < 0 || (sortOrder as number) > 1000000) throw new TrailsSyncInputError('sortOrder必须是合理的非负整数'); return { id: opaque(value.id, 'id'), portfolioId: opaque(value.portfolioId, 'portfolioId'), title: safeText(value.title, 'title', 160), summary: safeText(value.summary, 'summary', 4000), canonicalUrl: canonicalUrl(value.canonicalUrl), sortOrder: sortOrder as number }; };
const draftInput = (value: DurableExternalVideoReferenceMutation & DurableExternalVideoReferenceDraftInput) => { const allowed = new Set(['id', 'portfolioId', 'title', 'summary', 'canonicalUrl', 'sortOrder', 'mutationId', 'expectedResourceVersion']); for (const key of Object.keys(value as object)) if (!allowed.has(key)) throw new TrailsSyncInputError(`不允许字段:${key}`); return payload(value as unknown as Record<string, unknown>); };
const readPayload = (row: Row) => { try { const value = JSON.parse(row.payloadJson) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return payload({ ...(value as Record<string, unknown>), id: row.id, portfolioId: row.portfolioId, sortOrder: row.sortOrder }); } catch (error) { if (error instanceof TrailsSyncInputError) throw error; throw new TrailsSyncPersistenceError('外部视频引用载荷无效'); } };
const fromRow = (row: Row): DurableExternalVideoReference => ({ ...readPayload(row), tenantId: row.tenantId, ownerUserId: row.ownerUserId, status: row.status as DurableExternalVideoReferenceStatus, resourceVersion: version(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), ...(row.publishedAt ? { publishedAt: row.publishedAt.toISOString() } : {}), ...(row.archivedAt ? { archivedAt: row.archivedAt.toISOString() } : {}) });
export class TrailsDurableExternalVideoReferenceStaleVersionError extends Error { constructor(public readonly current: DurableExternalVideoReference) { super('外部视频引用版本已过期'); } }
export interface ExternalVideoReferenceModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId: string; status?: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface ExternalVideoReferenceMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<ITrailsDurableExternalVideoReferenceMutationTableAttributes | undefined>; create(row: ITrailsDurableExternalVideoReferenceMutationTableAttributes, options: Options): Promise<void>; }
export interface ExternalVideoReferenceAuditModel { create(row: ITrailsDurableExternalVideoReferenceAuditTableAttributes, options: Options): Promise<void>; }
export interface ExternalVideoReferencePortfolioModel { find(input: { tenantId: string; id: string }, options: Options): Promise<Portfolio | undefined>; }
export class MySqlDurableExternalVideoReferenceRepository implements DurableExternalVideoReferenceStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly references: ExternalVideoReferenceModel, private readonly mutations: ExternalVideoReferenceMutationModel, private readonly audits: ExternalVideoReferenceAuditModel, private readonly portfolios: ExternalVideoReferencePortfolioModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor) { const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return owner; }
  private async parent(tenantId: string, portfolioId: string, ownerUserId: string, tx: TrailsSyncTransaction, publicOnly = false) { const parent = await this.portfolios.find({ tenantId, id: portfolioId }, { transaction: tx }); if (!parent || parent.ownerUserId !== ownerUserId || (publicOnly && (parent.visibility !== 'public' || parent.lifecycle !== 'published'))) throw new TrailsSyncInputError('作品集不存在或不属于当前创作空间'); return parent; }
  private async mutation<T>(actor: Actor, input: DurableExternalVideoReferenceMutation, operation: string, work: (tx: TrailsSyncTransaction) => Promise<T>) { const mutationId = opaque(input.mutationId, 'mutationId'); if (input.expectedResourceVersion !== null) decimal(input.expectedResourceVersion, 'expectedResourceVersion'); const fingerprint = createHash('sha256').update(JSON.stringify({ operation, input })).digest('hex'); return this.connection.transaction(async transaction => { const prior = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId }, { transaction }); if (prior) { if (prior.fingerprint !== fingerprint) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(prior.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId, fingerprint, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async row(actor: Actor, id: string, tx: TrailsSyncTransaction) { const row = await this.references.find({ tenantId: actor.tenantId, id: opaque(id, 'id') }, { transaction: tx }); if (!row || row.ownerUserId !== this.owner(actor)) throw new TrailsSyncInputError('外部视频引用不存在或不属于当前创作空间'); await this.parent(row.tenantId, row.portfolioId, row.ownerUserId, tx); return row; }
  private async audit(actor: Actor, row: Row, mutationId: string, operation: string, fromVersion: string | undefined, tx: TrailsSyncTransaction) { await this.audits.create({ eventId: `external-video-reference-audit_${createHash('sha256').update(`${actor.tenantId}:${actor.userId}:${mutationId}`).digest('hex')}`, tenantId: row.tenantId, referenceId: row.id, actorUserId: actor.userId, ownerUserId: row.ownerUserId, mutationId, operation, ...(fromVersion ? { fromVersion } : {}), toVersion: version(row.resourceVersion), occurredAt: row.updatedAt }, { transaction: tx }); }
  async createDraft(actor: Actor, input: DurableExternalVideoReferenceMutation & DurableExternalVideoReferenceDraftInput) { return this.mutation(actor, input, 'create-draft', async tx => { if (input.expectedResourceVersion !== null) throw new TrailsSyncInputError('新外部视频引用必须使用null版本'); const values = draftInput(input); const owner = this.owner(actor); await this.parent(actor.tenantId, values.portfolioId, owner, tx); const time = this.now(); const row: Row = { tenantId: actor.tenantId, id: values.id, ownerUserId: owner, portfolioId: values.portfolioId, status: 'draft', sortOrder: values.sortOrder, resourceVersion: '1', payloadJson: JSON.stringify({ title: values.title, summary: values.summary, canonicalUrl: values.canonicalUrl }), createdAt: time, updatedAt: time }; const saved = await this.references.create(row, { transaction: tx }); await this.audit(actor, saved, input.mutationId, 'create-draft', undefined, tx); return fromRow(saved); }); }
  async updateDraft(actor: Actor, input: DurableExternalVideoReferenceMutation & DurableExternalVideoReferenceDraftInput) { return this.change(actor, input, 'update-draft', 'draft', async (row, tx) => { const values = draftInput(input); await this.parent(row.tenantId, values.portfolioId, row.ownerUserId, tx); return { ...row, portfolioId: values.portfolioId, sortOrder: values.sortOrder, payloadJson: JSON.stringify({ title: values.title, summary: values.summary, canonicalUrl: values.canonicalUrl }) }; }); }
  async publish(actor: Actor, input: DurableExternalVideoReferenceMutation & { id: string }) { return this.change(actor, input, 'publish', 'draft', row => ({ ...row, status: 'published', publishedAt: this.now() })); }
  async unpublish(actor: Actor, input: DurableExternalVideoReferenceMutation & { id: string }) { return this.change(actor, input, 'unpublish', 'published', row => ({ ...row, status: 'draft', publishedAt: undefined })); }
  async archive(actor: Actor, input: DurableExternalVideoReferenceMutation & { id: string }) { return this.change(actor, input, 'archive', undefined, row => ({ ...row, status: 'archived', archivedAt: this.now() })); }
  private async change(actor: Actor, input: DurableExternalVideoReferenceMutation & { id: string }, operation: string, required: DurableExternalVideoReferenceStatus | undefined, patch: (row: Row, tx: TrailsSyncTransaction) => Partial<Row> | Promise<Partial<Row>>) { return this.mutation(actor, input, operation, async tx => { const row = await this.row(actor, input.id, tx); if (input.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableExternalVideoReferenceStaleVersionError(fromRow(row)); if (row.status === 'archived' || (required && row.status !== required)) throw new TrailsSyncInputError('当前外部视频引用不允许该操作'); const time = this.now(); const next: Row = { ...row, ...(await patch(row, tx)), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: time }; const saved = await this.references.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction: tx }); if (!saved) throw new TrailsDurableExternalVideoReferenceStaleVersionError(fromRow(await this.row(actor, input.id, tx))); await this.audit(actor, saved, input.mutationId, operation, row.resourceVersion, tx); return fromRow(saved); }); }
  async listWorkspace(actor: Actor) { return this.connection.transaction(async tx => { const owner = this.owner(actor); const rows = await this.references.list({ tenantId: actor.tenantId, ownerUserId: owner }, { transaction: tx }); const result: DurableExternalVideoReference[] = []; for (const row of rows) { await this.parent(row.tenantId, row.portfolioId, owner, tx); result.push(fromRow(row)); } return result; }); }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>) { return this.connection.transaction(async tx => { const rows = await this.references.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, status: 'published' }, { transaction: tx }); const result: DurableExternalVideoReference[] = []; for (const row of rows) { try { await this.parent(row.tenantId, row.portfolioId, owner.userId, tx, true); result.push(fromRow(row)); } catch (error) { if (!(error instanceof TrailsSyncInputError)) throw error; } } return result; }); }
}
const row = (value: ITrailsDurableExternalVideoReferenceTableAttributes): Row => { if (!value.createdAt || !value.updatedAt) throw new TrailsSyncPersistenceError('外部视频引用行无效'); return { ...value, resourceVersion: version(value.resourceVersion), createdAt: value.createdAt, updatedAt: value.updatedAt }; };
const tx = (value: TrailsSyncTransaction) => { if (!(value instanceof Transaction)) throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); return value; };
export const createSequelizeDurableExternalVideoReferenceModels = (references: ModelStatic<TrailsDurableExternalVideoReferenceTable>, mutations: ModelStatic<TrailsDurableExternalVideoReferenceMutationTable>, audits: ModelStatic<TrailsDurableExternalVideoReferenceAuditTable>, portfolios: ModelStatic<any>) => ({ references: { async create(input: Row, options: Options) { return row((await references.create(input, { transaction: tx(options.transaction) })).get()); }, async find(input: { tenantId: string; id: string }, options: Options) { const transaction = tx(options.transaction); const value = await references.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return value ? row(value.get()) : undefined; }, async list(input: { tenantId: string; ownerUserId: string; status?: string }, options: Options) { return (await references.findAll({ where: input, order: [['sortOrder', 'ASC'], ['createdAt', 'ASC'], ['id', 'ASC']], transaction: tx(options.transaction) })).map(value => row(value.get())); }, async cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options) { const [changed] = await references.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction: tx(options.transaction) }); return changed === 1 ? input.next : undefined; } } as ExternalVideoReferenceModel, mutations: { async find(input: any, options: Options) { const transaction = tx(options.transaction); return (await mutations.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }))?.get(); }, async create(input: any, options: Options) { await mutations.create(input, { transaction: tx(options.transaction) }); } } as ExternalVideoReferenceMutationModel, audits: { async create(input: any, options: Options) { await audits.create(input, { transaction: tx(options.transaction) }); } } as ExternalVideoReferenceAuditModel, portfolios: { async find(input: any, options: Options) { const transaction = tx(options.transaction); const value = await portfolios.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return value ? value.get() as Portfolio : undefined; } } as ExternalVideoReferencePortfolioModel });
