import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsPublicSiteContentTableAttributes, TrailsPublicSiteContentTable } from 'db/mysql/models/trailsPublicSiteContent';
import { Actor, DEFAULT_PUBLIC_SITE_CHROME, DurablePublicSiteContent, DurablePublicSiteContentStore, EffectivePublicSiteContent, PublicChromeTarget } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError } from './mysqlPortfolioCategorySync';

type Row = Omit<ITrailsPublicSiteContentTableAttributes, 'createdAt' | 'updatedAt' | 'publishedAt'> & { createdAt: Date; updatedAt: Date; publishedAt?: Date };
type Connection = { transaction<T>(work: (transaction: object) => Promise<T>): Promise<T> };
const version = (value: unknown) => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : (() => { throw new TrailsSyncInputError('resourceVersion无效'); })();
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype;
const exact = (value: unknown, keys: readonly string[], label: string) => { if (!isRecord(value) || !Reflect.ownKeys(value).every(key => typeof key === 'string' && keys.includes(key)) || !Reflect.ownKeys(value).every(key => { const descriptor = Object.getOwnPropertyDescriptor(value, key); return descriptor?.enumerable && 'value' in descriptor; })) throw new TrailsSyncInputError(`${label}无效`); return value; };
const text = (value: unknown, maximum: number, label: string) => { if (typeof value !== 'string' || !value.trim() || value.trim().length > maximum || /[<>]|[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(value)) throw new TrailsSyncInputError(`${label}无效`); return value.trim(); };
const icpFilingNumber = (value: unknown, label: string) => { if (typeof value !== 'string') throw new TrailsSyncInputError(`${label}无效`); const normalized = value.trim(); if (normalized.length > 32 || /[<>]|[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]|\s/.test(normalized) || !/^[\u4E00-\u9FFF]{1,3}ICP备\d{4,12}号(?:-\d{1,3})?$/.test(normalized)) throw new TrailsSyncInputError(`${label}无效`); return normalized; };
const isIpv4Host = (host: string) => /^(?:25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})(?:\.(?:25[0-5]|2[0-4][0-9]|1?[0-9]{1,2})){3}$/.test(host);
const isDnsHost = (host: string) => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/i.test(host) && host.toLowerCase() !== 'localhost' && !isIpv4Host(host);
const contactHref = (value: string, label: string) => { try { const url = new URL(value); const authority = value.slice('https://'.length).split(/[/?#]/, 1)[0]; if (url.protocol !== 'https:' || !isDnsHost(url.hostname) || authority.includes(':') || url.username || url.password || url.port || url.pathname !== '/' || url.search || url.hash) throw new Error('unsafe'); return url.toString(); } catch { throw new TrailsSyncInputError(`${label}无效`); } };
const target = (value: unknown, label: string): PublicChromeTarget => { if (value === 'home' || value === 'editions' || value === 'stories' || value === 'trips' || value === 'locations' || value === 'about' || value === 'guestbook') return value; throw new TrailsSyncInputError(`${label}无效`); };
const defaultChrome = () => ({ navigation: DEFAULT_PUBLIC_SITE_CHROME.navigation.map(link => ({ ...link })), footer: { links: DEFAULT_PUBLIC_SITE_CHROME.footer.links.map(link => ({ ...link })), copyright: DEFAULT_PUBLIC_SITE_CHROME.footer.copyright } });
const chromeLinks = (value: unknown, minimum: number, label: string) => { if (!Array.isArray(value) || value.length < minimum || value.length > 7) throw new TrailsSyncInputError(`${label}无效`); const links = value.map((entry, index) => { const link = exact(entry, ['label', 'target'], `${label}[${index}]`); if (Reflect.ownKeys(link).length !== 2) throw new TrailsSyncInputError(`${label}无效`); return { label: text(link.label, 80, `${label}[${index}].label`), target: target(link.target, `${label}[${index}].target`) }; }); if (new Set(links.map(link => link.target)).size !== links.length) throw new TrailsSyncInputError(`${label}无效`); return links; };
const aboutProfileForbiddenFields = ['href', 'url', 'email', 'phone', 'location', 'region', 'address', 'coordinates', 'route', 'directions', 'access', 'meeting', 'media', 'reference', 'identity', 'privateLocation'];
const optionalOpaqueId = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{1,160}$/.test(value)) throw new TrailsSyncInputError(`${label}无效`); return value; };
const aboutText = (value: unknown, maximum: number, label: string) => { const normalized = text(value, maximum, label); if (/(?:\w+:\/\/|\bwww\.)/i.test(normalized) || /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i.test(normalized) || /(?:\+?\d[\d .()\-]{6,}\d)/.test(normalized) || /[-+]?\d{1,2}\.\d{3,}\s*,\s*[-+]?\d{1,3}\.\d{3,}/.test(normalized)) throw new TrailsSyncInputError(`${label}无效`); return normalized; };
const aboutProfile = (value: unknown) => { const profile = exact(value, ['professionalIdentity', 'practiceStatement', 'collaborationDirections', 'selectedCredentials', 'selectedProjects'], 'contentJson.aboutProfile'); const identity = exact(profile.professionalIdentity, ['headline', 'disciplines'], 'contentJson.aboutProfile.professionalIdentity'); if (Reflect.ownKeys(profile).length !== 5 || Reflect.ownKeys(identity).length !== 2 || aboutProfileForbiddenFields.some(key => key in profile || key in identity)) throw new TrailsSyncInputError('contentJson.aboutProfile无效'); const list = (raw: unknown, maximumItems: number, maximumText: number, label: string) => { if (!Array.isArray(raw) || raw.length > maximumItems) throw new TrailsSyncInputError(`${label}无效`); return raw.map((item, index) => aboutText(item, maximumText, `${label}[${index}]`)); }; if (!Array.isArray(profile.selectedProjects) || profile.selectedProjects.length > 6) throw new TrailsSyncInputError('contentJson.aboutProfile.selectedProjects无效'); return { professionalIdentity: { headline: aboutText(identity.headline, 120, 'contentJson.aboutProfile.professionalIdentity.headline'), disciplines: list(identity.disciplines, 8, 60, 'contentJson.aboutProfile.professionalIdentity.disciplines') }, practiceStatement: aboutText(profile.practiceStatement, 2000, 'contentJson.aboutProfile.practiceStatement'), collaborationDirections: list(profile.collaborationDirections, 6, 240, 'contentJson.aboutProfile.collaborationDirections'), selectedCredentials: list(profile.selectedCredentials, 8, 240, 'contentJson.aboutProfile.selectedCredentials'), selectedProjects: profile.selectedProjects.map((entry, index) => { const project = exact(entry, ['title', 'summary'], `contentJson.aboutProfile.selectedProjects[${index}]`); if (Reflect.ownKeys(project).length !== 2 || aboutProfileForbiddenFields.some(key => key in project)) throw new TrailsSyncInputError('contentJson.aboutProfile.selectedProjects无效'); return { title: aboutText(project.title, 120, `contentJson.aboutProfile.selectedProjects[${index}].title`), summary: aboutText(project.summary, 600, `contentJson.aboutProfile.selectedProjects[${index}].summary`) }; }) }; };
const normalizeContent = (value: unknown): EffectivePublicSiteContent => {
  const document = exact(value, ['displayName', 'biography', 'contactLinks', 'licensingCopy', 'seo', 'aboutProfile', 'aboutPortraitMediaId', 'chrome'], 'contentJson');
  if (!['displayName', 'biography', 'contactLinks', 'licensingCopy', 'seo'].every(key => key in document) || Reflect.ownKeys(document).length !== 5 + Number(document.aboutProfile !== undefined) + Number(document.aboutPortraitMediaId !== undefined) + Number(document.chrome !== undefined)) throw new TrailsSyncInputError('contentJson无效');
  const biography = exact(document.biography, ['plainText'], 'contentJson.biography'); const seo = exact(document.seo, ['title', 'description'], 'contentJson.seo');
  if (Reflect.ownKeys(biography).length !== 1 || Reflect.ownKeys(seo).length !== 2 || !Array.isArray(document.contactLinks) || document.contactLinks.length > 10) throw new TrailsSyncInputError('contentJson无效');
  const contactLinks: EffectivePublicSiteContent['contactLinks'] = document.contactLinks.map((entry, index) => { const link = exact(entry, ['kind', 'href'], `contentJson.contactLinks[${index}]`); if (Reflect.ownKeys(link).length !== 2 || (link.kind !== 'website' && link.kind !== 'instagram' && link.kind !== 'linkedin') || typeof link.href !== 'string') throw new TrailsSyncInputError('contentJson无效'); return { kind: link.kind, href: contactHref(link.href, `contentJson.contactLinks[${index}].href`) }; });
  const chrome = document.chrome === undefined ? defaultChrome() : (() => { const raw = exact(document.chrome, ['navigation', 'footer'], 'contentJson.chrome'); if (Reflect.ownKeys(raw).length !== 2) throw new TrailsSyncInputError('contentJson.chrome无效'); const footer = exact(raw.footer, ['links', 'copyright', 'icpFilingNumber'], 'contentJson.chrome.footer'); if (!('links' in footer) || !('copyright' in footer) || ![2, 3].includes(Reflect.ownKeys(footer).length)) throw new TrailsSyncInputError('contentJson.chrome.footer无效'); return { navigation: chromeLinks(raw.navigation, 1, 'contentJson.chrome.navigation'), footer: { links: chromeLinks(footer.links, 0, 'contentJson.chrome.footer.links'), copyright: text(footer.copyright, 160, 'contentJson.chrome.footer.copyright'), ...(footer.icpFilingNumber === undefined ? {} : { icpFilingNumber: icpFilingNumber(footer.icpFilingNumber, 'contentJson.chrome.footer.icpFilingNumber') }) } }; })();
  return { displayName: text(document.displayName, 120, 'contentJson.displayName'), biography: { plainText: text(biography.plainText, 50000, 'contentJson.biography.plainText') }, contactLinks, licensingCopy: text(document.licensingCopy, 10000, 'contentJson.licensingCopy'), seo: { title: text(seo.title, 160, 'contentJson.seo.title'), description: text(seo.description, 320, 'contentJson.seo.description') }, ...(document.aboutProfile === undefined ? {} : { aboutProfile: aboutProfile(document.aboutProfile) }), ...(document.aboutPortraitMediaId === undefined ? {} : { aboutPortraitMediaId: optionalOpaqueId(document.aboutPortraitMediaId, 'contentJson.aboutPortraitMediaId') }), chrome };
};
const parsedContent = (serialized: string) => { try { return normalizeContent(JSON.parse(serialized)); } catch (error: unknown) { if (error instanceof TrailsSyncInputError) throw error; throw new TrailsSyncInputError('contentJson无效'); } };
const content = (row: Row): DurablePublicSiteContent => ({ tenantId: row.tenantId, ownerUserId: row.ownerUserId, status: row.status, ...parsedContent(row.contentJson), resourceVersion: version(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), ...(row.publishedAt ? { publishedAt: row.publishedAt.toISOString() } : {}) });
export class TrailsPublicSiteContentStaleVersionError extends Error {}
export interface PublicSiteContentModel { find(input: { tenantId: string; ownerUserId: string }, transaction: object): Promise<Row | undefined>; create(input: Row, transaction: object): Promise<Row>; update(current: Row, next: Row, transaction: object): Promise<Row | undefined>; }
export class MySqlPublicSiteContentRepository implements DurablePublicSiteContentStore {
  constructor(private readonly connection: Connection, private readonly model: PublicSiteContentModel, private readonly now: () => Date = () => new Date()) {}
  async readWorkspace(actor: Actor) { const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return this.connection.transaction(async tx => { const row = await this.model.find({ tenantId: actor.tenantId, ownerUserId: owner }, tx); return row && content(row); }); }
  async saveDraft(actor: Actor, input: EffectivePublicSiteContent & { resourceVersion: string | null }) { return this.write(actor, input.resourceVersion, 'draft', input); }
  async publish(actor: Actor, input: { resourceVersion: string }) { return this.write(actor, input.resourceVersion, 'published'); }
  async unpublish(actor: Actor, input: { resourceVersion: string }) { return this.write(actor, input.resourceVersion, 'draft'); }
  async readPublic(owner: Pick<Actor, 'tenantId' | 'userId'>) { return this.connection.transaction(async tx => { const row = await this.model.find({ tenantId: owner.tenantId, ownerUserId: owner.userId }, tx); return row?.status === 'published' ? content(row) : undefined; }); }
  private async write(actor: Actor, expected: string | null, status: 'draft' | 'published', nextContent?: EffectivePublicSiteContent & { resourceVersion: string | null }) {
    const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限');
    return this.connection.transaction(async tx => { const current = await this.model.find({ tenantId: actor.tenantId, ownerUserId: owner }, tx); if (!current && (expected !== null || !nextContent)) throw new TrailsSyncInputError('公开内容草稿不存在'); if (current && version(current.resourceVersion) !== expected) throw new TrailsPublicSiteContentStaleVersionError(); const existingContent = current ? parsedContent(current.contentJson) : undefined; const canonicalContent = nextContent ? (() => { const { resourceVersion: _resourceVersion, ...editorialContent } = nextContent; return normalizeContent(editorialContent); })() : existingContent; if (!canonicalContent) throw new TrailsSyncInputError('公开内容草稿不存在'); const timestamp = this.now(); const row: Row = { tenantId: actor.tenantId, ownerUserId: owner, status, contentJson: JSON.stringify(canonicalContent), resourceVersion: String(BigInt(current?.resourceVersion || '0') + BigInt(1)), createdAt: current?.createdAt || timestamp, updatedAt: timestamp, publishedAt: status === 'published' ? timestamp : undefined }; const saved = current ? await this.model.update(current, row, tx) : await this.model.create(row, tx); if (!saved) throw new TrailsPublicSiteContentStaleVersionError(); return content(saved); });
  }
}
export const createSequelizePublicSiteContentModel = (model: ModelStatic<TrailsPublicSiteContentTable>): PublicSiteContentModel => ({
  async find(input, transaction) { if (!(transaction instanceof Transaction)) throw new Error('managed transaction required'); const found = await model.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return found ? found.get() as Row : undefined; },
  async create(input, transaction) { return (await model.create(input, { transaction: transaction as Transaction })).get() as Row; },
  async update(current, next, transaction) { const [affected] = await model.update(next, { where: { tenantId: current.tenantId, ownerUserId: current.ownerUserId, resourceVersion: current.resourceVersion }, transaction: transaction as Transaction }); return affected === 1 ? next : undefined; },
});
