import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsDurableMediaCommerceTableAttributes, TrailsDurableMediaCommerceTable } from 'db/mysql/models/trailsDurableMediaCommerce';
import { ITrailsDurableMediaCommerceMutationTableAttributes, TrailsDurableMediaCommerceMutationTable } from 'db/mysql/models/trailsDurableMediaCommerceMutation';
import { Actor, CommercialLicenseInquiry, DownloadEntitlement, DownloadLicenseRequest, DurableCommerceMutation, DurableMedia, DurableMediaCommerceStore, ManualOrder, PrintEdition } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type RecordType = 'media' | 'edition' | 'inquiry' | 'request' | 'entitlement' | 'order';
type Row = Omit<ITrailsDurableMediaCommerceTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type MutationRow = ITrailsDurableMediaCommerceMutationTableAttributes;
type Options = { transaction: TrailsSyncTransaction };
export class TrailsDurableMediaCommerceStaleVersionError extends Error {}
const text = (value: unknown, label: string, max: number): string => { if (typeof value !== 'string' || !value.trim() || value.length > max) throw new TrailsSyncInputError(`${label}无效`); return value.trim(); };
const version = (value: unknown): string => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError('expectedResourceVersion必须是规范十进制字符串'); return value; };
const money = (value: unknown, label: string): number => { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) throw new TrailsSyncInputError(`${label}必须是非负安全整数最小货币单位`); return value; };
const currency = (value: unknown): string => { if (typeof value !== 'string' || !/^[A-Z]{3}$/.test(value)) throw new TrailsSyncInputError('currency必须是3位大写ISO货币代码'); return value; };
const fingerprint = (operation: string, input: unknown) => createHash('sha256').update(JSON.stringify({ operation, input })).digest('hex');
const sequelizeTransaction = (transaction: TrailsSyncTransaction): Transaction => { if (transaction instanceof Transaction) return transaction; throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); };
const databaseVersion = (value: unknown): string => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : typeof value === 'number' && Number.isSafeInteger(value) ? String(value) : typeof value === 'bigint' ? value.toString() : (() => { throw new TrailsSyncPersistenceError('commerce version invalid'); })();
const parsed = (row: Row): Record<string, unknown> => { try { const value: unknown = JSON.parse(row.payloadJson); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return value as Record<string, unknown>; } catch { throw new TrailsSyncPersistenceError('commerce payload invalid'); } };
const fromRow = <T>(row: Row): T => ({ ...parsed(row), id: row.id, tenantId: row.tenantId, ownerUserId: row.ownerUserId, resourceVersion: databaseVersion(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as T);
export interface CommerceModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId?: string; buyerUserId?: string; recordType?: RecordType; status?: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface CommerceMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<MutationRow | undefined>; create(row: MutationRow, options: Options): Promise<void>; }

export class MySqlDurableMediaCommerceRepository implements DurableMediaCommerceStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly records: CommerceModel, private readonly mutations: CommerceMutationModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor): string { const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return owner; }
  private async mutate<T>(actor: Actor, mutation: DurableCommerceMutation, operation: string, work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> { text(mutation.mutationId, 'mutationId', 160); if (mutation.expectedResourceVersion !== null) version(mutation.expectedResourceVersion); const expected = fingerprint(operation, mutation); return this.connection.transaction(async transaction => { const prior = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId: mutation.mutationId }, { transaction }); if (prior) { if (prior.fingerprint !== expected) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(prior.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId: mutation.mutationId, fingerprint: expected, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async load(transaction: TrailsSyncTransaction, tenantId: string, id: string, type: RecordType): Promise<Row> { const row = await this.records.find({ tenantId, id }, { transaction }); if (!row || row.recordType !== type) throw new TrailsSyncInputError('资源不存在'); return row; }
  private async transition<T extends { status: string }>(actor: Actor, mutation: DurableCommerceMutation & { id: string; status: string }, type: RecordType, allowed: Record<string, string[]>, ownerRequired: boolean, transform?: (value: Record<string, unknown>) => Record<string, unknown>): Promise<T> { return this.mutate(actor, mutation, `${type}:transition`, async transaction => { const row = await this.load(transaction, actor.tenantId, text(mutation.id, 'id', 160), type); if ((ownerRequired ? row.ownerUserId !== this.owner(actor) : row.buyerUserId !== actor.userId)) throw new TrailsSyncInputError('资源不属于当前账号'); if (mutation.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); if (!allowed[row.status]?.includes(mutation.status)) throw new TrailsSyncInputError('当前状态不允许该转换'); const next: Row = { ...row, status: mutation.status, payloadJson: JSON.stringify({ ...parsed(row), status: mutation.status, ...(transform ? transform(parsed(row)) : {}) }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); return fromRow<T>(saved); }); }
  async createMedia(actor: Actor, m: DurableCommerceMutation & { id: string; title: string; summary: string; derivativeReferences: Array<{ reference: string; width?: number; height?: number }> }): Promise<DurableMedia> { const owner = this.owner(actor); const refs = m.derivativeReferences; if (!Array.isArray(refs) || refs.some(x => !x || typeof x.reference !== 'string' || !/^[A-Za-z0-9_-]{1,160}$/.test(x.reference) || ('url' in x) || ('objectKey' in x))) throw new TrailsSyncInputError('derivativeReferences只能包含安全不透明引用'); return this.mutate(actor, m, 'media:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const time = this.now(); const payload = { title: text(m.title, 'title', 160), summary: text(m.summary, 'summary', 65535), status: 'draft', publicDerivativeReferences: refs.map(x => ({ reference: x.reference, ...(Number.isSafeInteger(x.width) && x.width! > 0 ? { width: x.width } : {}), ...(Number.isSafeInteger(x.height) && x.height! > 0 ? { height: x.height } : {}) })) }; return fromRow<DurableMedia>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: owner, recordType: 'media', status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async transitionMedia(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'draft' | 'published' | 'withdrawn' }): Promise<DurableMedia> {
    if (m.status !== 'withdrawn') return this.transition(actor, m, 'media', { draft: ['published'], published: ['withdrawn'], withdrawn: [] }, true);
    const owner = this.owner(actor);
    return this.mutate(actor, m, 'media:transition', async transaction => {
      const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'media');
      if (row.ownerUserId !== owner) throw new TrailsSyncInputError('资源不属于当前账号');
      if (m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      if (row.status !== 'published') throw new TrailsSyncInputError('当前状态不允许该转换');
      const editions = await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType: 'edition', status: 'sellable' }, { transaction });
      if (editions.some(edition => parsed(edition).mediaId === row.id)) throw new TrailsSyncInputError('存在可售版次时不能撤回媒体；请先分别撤回版次');
      const next: Row = { ...row, status: 'withdrawn', payloadJson: JSON.stringify({ ...parsed(row), status: 'withdrawn' }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() };
      const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction });
      if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      return fromRow<DurableMedia>(saved);
    });
  }
  async createEdition(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string; title: string; description: string; currency: string; priceMinor: number }): Promise<PrintEdition> { const owner = this.owner(actor); return this.mutate(actor, m, 'edition:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const media = await this.load(transaction, actor.tenantId, text(m.mediaId, 'mediaId', 160), 'media'); if (media.ownerUserId !== owner) throw new TrailsSyncInputError('媒体不属于当前创作空间'); const time = this.now(); const payload = { mediaId: media.id, title: text(m.title, 'title', 160), description: text(m.description, 'description', 65535), currency: currency(m.currency), priceMinor: money(m.priceMinor, 'priceMinor'), status: 'draft' }; return fromRow<PrintEdition>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: owner, recordType: 'edition', status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async transitionEdition(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'draft' | 'sellable' | 'withdrawn' }): Promise<PrintEdition> {
    if (m.status !== 'sellable') return this.transition(actor, m, 'edition', { draft: ['sellable'], sellable: ['withdrawn'], withdrawn: [] }, true);
    const owner = this.owner(actor);
    return this.mutate(actor, m, 'edition:transition', async transaction => {
      const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'edition');
      if (row.ownerUserId !== owner) throw new TrailsSyncInputError('资源不属于当前账号');
      if (m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      if (row.status !== 'draft') throw new TrailsSyncInputError('当前状态不允许该转换');
      const mediaId = text(parsed(row).mediaId, 'mediaId', 160);
      const media = await this.load(transaction, actor.tenantId, mediaId, 'media');
      if (media.ownerUserId !== owner || media.status !== 'published') throw new TrailsSyncInputError('只有已发布的父媒体可以使版次可售');
      const next: Row = { ...row, status: 'sellable', payloadJson: JSON.stringify({ ...parsed(row), status: 'sellable' }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() };
      const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction });
      if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      return fromRow<PrintEdition>(saved);
    });
  }
  async inquireCommercial(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string; message: string }): Promise<CommercialLicenseInquiry> { return this.buyerCreate(actor, m, 'inquiry', { mediaId: text(m.mediaId, 'mediaId', 160), message: text(m.message, 'message', 4000), status: 'submitted' }); }
  async requestDownloadLicense(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string }): Promise<DownloadLicenseRequest> { return this.buyerCreate(actor, m, 'request', { mediaId: text(m.mediaId, 'mediaId', 160), status: 'requested' }); }
  private async buyerCreate<T>(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string }, type: 'inquiry' | 'request', payload: Record<string, unknown>): Promise<T> { return this.mutate(actor, m, `${type}:create`, async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const media = await this.load(transaction, actor.tenantId, text(m.mediaId, 'mediaId', 160), 'media'); if (media.status !== 'published') throw new TrailsSyncInputError('媒体不可请求'); const time = this.now(); return fromRow<T>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: media.ownerUserId, buyerUserId: actor.userId, recordType: type, status: String(payload.status), resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async decideDownloadLicense(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'granted' | 'declined' | 'revoked' }): Promise<DownloadLicenseRequest> { const owner = this.owner(actor); return this.mutate(actor, m, 'request:decide', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'request'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); const transitions: Record<string, string[]> = { requested: ['granted', 'declined'], granted: ['revoked'], declined: [], revoked: [] }; if (!transitions[row.status]?.includes(m.status)) throw new TrailsSyncInputError('当前状态不允许该转换'); const content = parsed(row); let entitlementId: string | undefined = typeof content.entitlementId === 'string' ? content.entitlementId : undefined; if (m.status === 'granted') { entitlementId = `entitlement_${row.id}`; const time = this.now(); await this.records.create({ tenantId: row.tenantId, id: entitlementId, ownerUserId: row.ownerUserId, buyerUserId: row.buyerUserId, recordType: 'entitlement', status: 'active', resourceVersion: '1', payloadJson: JSON.stringify({ mediaId: content.mediaId, requestId: row.id, status: 'active' }), createdAt: time, updatedAt: time }, { transaction }); } if (m.status === 'revoked' && entitlementId) { const entitlement = await this.load(transaction, actor.tenantId, entitlementId, 'entitlement'); await this.records.cas({ tenantId: actor.tenantId, id: entitlement.id, expectedVersion: entitlement.resourceVersion, next: { ...entitlement, status: 'revoked', payloadJson: JSON.stringify({ ...parsed(entitlement), status: 'revoked' }), resourceVersion: (BigInt(entitlement.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() } }, { transaction }); } const next: Row = { ...row, status: m.status, payloadJson: JSON.stringify({ ...content, status: m.status, ...(entitlementId ? { entitlementId } : {}) }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); return fromRow<DownloadLicenseRequest>(saved); }); }
  async createOrder(actor: Actor, m: DurableCommerceMutation & { id: string; editionId: string }): Promise<ManualOrder> { return this.mutate(actor, m, 'order:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const edition = await this.load(transaction, actor.tenantId, text(m.editionId, 'editionId', 160), 'edition'); if (edition.status !== 'sellable') throw new TrailsSyncInputError('版本不可销售'); const value = parsed(edition); const time = this.now(); const payload = { editionId: edition.id, titleSnapshot: value.title, currencySnapshot: value.currency, priceMinorSnapshot: value.priceMinor, status: 'submitted', paidMinor: 0, refundedMinor: 0 }; return fromRow<ManualOrder>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: edition.ownerUserId, buyerUserId: actor.userId, recordType: 'order', status: 'submitted', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async transitionOrder(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'submitted' | 'payment-recorded' | 'fulfilled' | 'refunded' | 'cancelled'; refundMinor?: number }): Promise<ManualOrder> { const owner = this.owner(actor); return this.mutate(actor, m, 'order:transition', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'order'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); const allowed: Record<string, string[]> = { submitted: ['payment-recorded', 'cancelled'], 'payment-recorded': ['fulfilled', 'refunded'], fulfilled: ['refunded'], refunded: [], cancelled: [] }; if (!allowed[row.status]?.includes(m.status)) throw new TrailsSyncInputError('当前状态不允许该转换'); const value = parsed(row); const paidMinor = m.status === 'payment-recorded' ? Number(value.priceMinorSnapshot) : Number(value.paidMinor); const refundedMinor = m.status === 'refunded' ? money(m.refundMinor, 'refundMinor') : Number(value.refundedMinor); if (refundedMinor > paidMinor) throw new TrailsSyncInputError('退款不能超过已记录付款'); const next: Row = { ...row, status: m.status, payloadJson: JSON.stringify({ ...value, status: m.status, paidMinor, refundedMinor }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); return fromRow<ManualOrder>(saved); }); }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>) { return this.connection.transaction(async transaction => { const media = (await this.records.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, recordType: 'media', status: 'published' }, { transaction })).map(row => fromRow<DurableMedia>(row)); const ids = new Set(media.map(x => x.id)); const editions = (await this.records.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, recordType: 'edition', status: 'sellable' }, { transaction })).map(row => fromRow<PrintEdition>(row)).filter(x => ids.has(x.mediaId)); return { media, editions }; }); }
  async listBuyer(actor: Actor) { return this.connection.transaction(async transaction => { const list = async <T>(recordType: RecordType) => (await this.records.list({ tenantId: actor.tenantId, buyerUserId: actor.userId, recordType }, { transaction })).map(row => fromRow<T>(row)); return { inquiries: await list<CommercialLicenseInquiry>('inquiry'), requests: await list<DownloadLicenseRequest>('request'), entitlements: await list<DownloadEntitlement>('entitlement'), orders: await list<ManualOrder>('order') }; }); }
  async listOwner(actor: Actor) { const owner = this.owner(actor); return this.connection.transaction(async transaction => { const list = async <T>(recordType: RecordType) => (await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType }, { transaction })).map(row => fromRow<T>(row)); return { media: await list<DurableMedia>('media'), editions: await list<PrintEdition>('edition'), inquiries: await list<CommercialLicenseInquiry>('inquiry'), requests: await list<DownloadLicenseRequest>('request'), entitlements: await list<DownloadEntitlement>('entitlement'), orders: await list<ManualOrder>('order') }; }); }
}
const row = (attributes: ITrailsDurableMediaCommerceTableAttributes): Row => { if (!attributes.createdAt || !attributes.updatedAt) throw new TrailsSyncPersistenceError('commerce row invalid'); return { ...attributes, resourceVersion: databaseVersion(attributes.resourceVersion), createdAt: attributes.createdAt, updatedAt: attributes.updatedAt }; };
export const createSequelizeDurableMediaCommerceModels = (records: ModelStatic<TrailsDurableMediaCommerceTable>, mutations: ModelStatic<TrailsDurableMediaCommerceMutationTable>): { records: CommerceModel; mutations: CommerceMutationModel } => ({ records: { async create(input, o) { return row((await records.create(input, { transaction: sequelizeTransaction(o.transaction) })).get()); }, async find(input, o) { const tx = sequelizeTransaction(o.transaction); const found = await records.findOne({ where: input, transaction: tx, lock: tx.LOCK.UPDATE }); return found ? row(found.get()) : undefined; }, async list(input, o) { return (await records.findAll({ where: input, order: [['createdAt', 'ASC'], ['id', 'ASC']], transaction: sequelizeTransaction(o.transaction) })).map(found => row(found.get())); }, async cas(input, o) { const tx = sequelizeTransaction(o.transaction); const [affected] = await records.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction: tx }); return affected === 1 ? input.next : undefined; } }, mutations: { async find(input, o) { const tx = sequelizeTransaction(o.transaction); const found = await mutations.findOne({ where: input, transaction: tx, lock: tx.LOCK.UPDATE }); return found?.get(); }, async create(input, o) { await mutations.create(input, { transaction: sequelizeTransaction(o.transaction) }); } } });
