import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsDurableMediaCommerceTableAttributes, TrailsDurableMediaCommerceTable } from 'db/mysql/models/trailsDurableMediaCommerce';
import { ITrailsDurableMediaCommerceMutationTableAttributes, TrailsDurableMediaCommerceMutationTable } from 'db/mysql/models/trailsDurableMediaCommerceMutation';
import { Actor, CommercialLicenseInquiry, DownloadEntitlement, DownloadLicenseRequest, DurableCommerceMutation, DurableMedia, DurableMediaCommerceStore, ManualOrder, ManualSalesOrder, ManualSalesOrderStatus, PrintEdition, SalesConfiguration, SalesInventoryMode, SalesMode, SalesProduct, SalesProductSku, SalesProductStatus, SalesProductType, SalesWorkspace } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type RecordType = 'media' | 'edition' | 'inquiry' | 'request' | 'entitlement' | 'order' | 'sales-configuration' | 'sales-product' | 'sales-order';
type Row = Omit<ITrailsDurableMediaCommerceTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type MutationRow = ITrailsDurableMediaCommerceMutationTableAttributes;
type Options = { transaction: TrailsSyncTransaction };
export class TrailsDurableMediaCommerceStaleVersionError extends Error {}
const text = (value: unknown, label: string, max: number): string => { if (typeof value !== 'string' || !value.trim() || value.length > max) throw new TrailsSyncInputError(`${label}无效`); return value.trim(); };
const version = (value: unknown): string => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError('expectedResourceVersion必须是规范十进制字符串'); return value; };
const money = (value: unknown, label: string): number => { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) throw new TrailsSyncInputError(`${label}必须是非负安全整数最小货币单位`); return value; };
const currency = (value: unknown): string => { if (typeof value !== 'string' || !/^[A-Z]{3}$/.test(value)) throw new TrailsSyncInputError('currency必须是3位大写ISO货币代码'); return value; };
const positiveInteger = (value: unknown, label: string, maximum: number): number => { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 1 || value > maximum) throw new TrailsSyncInputError(`${label}必须是1至${maximum}的安全整数`); return value; };
const optionalText = (value: unknown, label: string, maximum: number): string | undefined => value === undefined || value === null || value === '' ? undefined : text(value, label, maximum);
const salesProductType = (value: unknown): SalesProductType => value === 'postcard-set' || value === 'photographic-print' || value === 'printed-work' ? value : (() => { throw new TrailsSyncInputError('商品类型无效'); })();
const salesProductStatus = (value: unknown): SalesProductStatus => value === 'draft' || value === 'ready' || value === 'archived' ? value : (() => { throw new TrailsSyncInputError('商品状态无效'); })();
const salesMode = (value: unknown): SalesMode => value === 'disabled' || value === 'manual' || value === 'provider-checkout' ? value : (() => { throw new TrailsSyncInputError('销售模式无效'); })();
const manualSalesOrderStatus = (value: unknown): ManualSalesOrderStatus => value === 'awaiting-payment' || value === 'payment-confirmed' || value === 'in-production' || value === 'shipped' || value === 'completed' || value === 'cancelled' || value === 'refund-pending' || value === 'refunded' ? value : (() => { throw new TrailsSyncInputError('人工订单状态无效'); })();
const salesSkus = (value: unknown): SalesProductSku[] => {
  if (!Array.isArray(value) || value.length < 1 || value.length > 24) throw new TrailsSyncInputError('商品规格必须为1至24项');
  const ids = new Set<string>();
  return value.map((item, index) => {
    if (!item || typeof item !== 'object' || Array.isArray(item)) throw new TrailsSyncInputError(`商品规格${index + 1}无效`);
    const raw = item as Record<string, unknown>;
    if (!['id', 'label', 'priceMinor', 'inventoryMode', 'stockQuantity'].includes('id') || !Object.keys(raw).every(key => ['id', 'label', 'priceMinor', 'inventoryMode', 'stockQuantity'].includes(key))) throw new TrailsSyncInputError('商品规格包含不允许字段');
    const id = text(raw.id, '规格编号', 64);
    if (!/^[A-Za-z0-9_-]+$/.test(id) || ids.has(id)) throw new TrailsSyncInputError('规格编号必须唯一且仅包含字母、数字、下划线或连字符');
    ids.add(id);
    const inventoryMode: SalesInventoryMode = raw.inventoryMode === 'finite' || raw.inventoryMode === 'made-to-order' ? raw.inventoryMode : (() => { throw new TrailsSyncInputError('库存模式无效'); })();
    const priceMinor = positiveInteger(raw.priceMinor, '规格价格', 100_000_000);
    if (inventoryMode === 'finite') return { id, label: text(raw.label, '规格名称', 120), priceMinor, inventoryMode, stockQuantity: positiveInteger(raw.stockQuantity, '有限库存', 100_000) };
    if (raw.stockQuantity !== undefined) throw new TrailsSyncInputError('按需制作规格不能填写库存');
    return { id, label: text(raw.label, '规格名称', 120), priceMinor, inventoryMode };
  });
};
const fingerprint = (operation: string, input: unknown) => createHash('sha256').update(JSON.stringify({ operation, input })).digest('hex');
const sequelizeTransaction = (transaction: TrailsSyncTransaction): Transaction => { if (transaction instanceof Transaction) return transaction; throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); };
const databaseVersion = (value: unknown): string => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : typeof value === 'number' && Number.isSafeInteger(value) ? String(value) : typeof value === 'bigint' ? value.toString() : (() => { throw new TrailsSyncPersistenceError('commerce version invalid'); })();
const parsed = (row: Row): Record<string, unknown> => { try { const value: unknown = JSON.parse(row.payloadJson); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return value as Record<string, unknown>; } catch { throw new TrailsSyncPersistenceError('commerce payload invalid'); } };
const fromRow = <T>(row: Row): T => ({ ...parsed(row), id: row.id, tenantId: row.tenantId, ownerUserId: row.ownerUserId, resourceVersion: databaseVersion(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as T);
export interface CommerceModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId?: string; buyerUserId?: string; recordType?: RecordType; status?: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface CommerceMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<MutationRow | undefined>; create(row: MutationRow, options: Options): Promise<void>; }

export class MySqlDurableMediaCommerceRepository implements DurableMediaCommerceStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly records: CommerceModel, private readonly mutations: CommerceMutationModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor): string { const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return owner; }
  private async mutate<T>(actor: Actor, mutation: DurableCommerceMutation, operation: string, work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> { text(mutation.mutationId, 'mutationId', 160); if (mutation.expectedResourceVersion !== null) version(mutation.expectedResourceVersion); const expected = fingerprint(operation, mutation); return this.connection.transaction(async transaction => { const prior = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId: mutation.mutationId }, { transaction }); if (prior) { if (prior.fingerprint !== expected) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(prior.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId: mutation.mutationId, fingerprint: expected, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async load(transaction: TrailsSyncTransaction, tenantId: string, id: string, type: RecordType): Promise<Row> { const row = await this.records.find({ tenantId, id }, { transaction }); if (!row || row.recordType !== type) throw new TrailsSyncInputError('资源不存在'); return row; }
  private async transition<T extends { status: string }>(actor: Actor, mutation: DurableCommerceMutation & { id: string; status: string }, type: RecordType, allowed: Record<string, string[]>, ownerRequired: boolean, transform?: (value: Record<string, unknown>) => Record<string, unknown>): Promise<T> { return this.mutate(actor, mutation, `${type}:transition`, async transaction => { const row = await this.load(transaction, actor.tenantId, text(mutation.id, 'id', 160), type); if ((ownerRequired ? row.ownerUserId !== this.owner(actor) : row.buyerUserId !== actor.userId)) throw new TrailsSyncInputError('资源不属于当前账号'); if (mutation.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); if (!allowed[row.status]?.includes(mutation.status)) throw new TrailsSyncInputError('当前状态不允许该转换'); const next: Row = { ...row, status: mutation.status, payloadJson: JSON.stringify({ ...parsed(row), status: mutation.status, ...(transform ? transform(parsed(row)) : {}) }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); return fromRow<T>(saved); }); }
  async createMedia(actor: Actor, m: DurableCommerceMutation & { id: string; title: string; summary: string; derivativeReferences: Array<{ reference: string; width?: number; height?: number }> }): Promise<DurableMedia> { const owner = this.owner(actor); const refs = m.derivativeReferences; if (!Array.isArray(refs) || refs.some(x => !x || typeof x.reference !== 'string' || !/^[A-Za-z0-9_-]{1,160}$/.test(x.reference) || ('url' in x) || ('objectKey' in x))) throw new TrailsSyncInputError('derivativeReferences只能包含安全不透明引用'); return this.mutate(actor, m, 'media:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const time = this.now(); const payload = { title: text(m.title, 'title', 160), summary: text(m.summary, 'summary', 65535), status: 'draft', publicDerivativeReferences: refs.map(x => ({ reference: x.reference, ...(Number.isSafeInteger(x.width) && x.width! > 0 ? { width: x.width } : {}), ...(Number.isSafeInteger(x.height) && x.height! > 0 ? { height: x.height } : {}) })) }; return fromRow<DurableMedia>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: owner, recordType: 'media', status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async updateMedia(actor: Actor, m: DurableCommerceMutation & { id: string; title: string; summary: string }): Promise<DurableMedia> {
    const owner = this.owner(actor);
    return this.mutate(actor, m, 'media:update', async transaction => {
      const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'media');
      if (row.ownerUserId !== owner) throw new TrailsSyncInputError('资源不属于当前账号');
      if (m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      if (row.status !== 'draft' && row.status !== 'withdrawn') throw new TrailsSyncInputError('已发布媒体须先撤回后才能编辑');
      // An edited withdrawal becomes a new owner draft. It remains private until
      // the owner explicitly publishes it again, while preserving the asset.
      const nextStatus = row.status === 'withdrawn' ? 'draft' : row.status;
      const next: Row = { ...row, status: nextStatus, payloadJson: JSON.stringify({ ...parsed(row), title: text(m.title, 'title', 160), summary: text(m.summary, 'summary', 65535), status: nextStatus }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() };
      const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction });
      if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      return fromRow<DurableMedia>(saved);
    });
  }
  async transitionMedia(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'draft' | 'published' | 'withdrawn' }): Promise<DurableMedia> {
    if (m.status !== 'withdrawn') return this.transition(actor, m, 'media', { draft: ['published'], published: ['withdrawn'], withdrawn: [] }, true);
    const owner = this.owner(actor);
    return this.mutate(actor, m, 'media:transition', async transaction => {
      const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'media');
      if (row.ownerUserId !== owner) throw new TrailsSyncInputError('资源不属于当前账号');
      if (m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      if (row.status !== 'published') throw new TrailsSyncInputError('当前状态不允许该转换');
      const editions = await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType: 'edition', status: 'sellable' }, { transaction });
      if (editions.some(edition => parsed(edition).mediaId === row.id)) throw new TrailsSyncInputError('存在可售版次时不能撤回媒体；请先分别撤回版次');
      const next: Row = { ...row, status: 'withdrawn', payloadJson: JSON.stringify({ ...parsed(row), status: 'withdrawn' }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() };
      const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction });
      if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      return fromRow<DurableMedia>(saved);
    });
  }
  async createEdition(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string; title: string; description: string; currency: string; priceMinor: number }): Promise<PrintEdition> { const owner = this.owner(actor); return this.mutate(actor, m, 'edition:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const media = await this.load(transaction, actor.tenantId, text(m.mediaId, 'mediaId', 160), 'media'); if (media.ownerUserId !== owner) throw new TrailsSyncInputError('媒体不属于当前创作空间'); const time = this.now(); const payload = { mediaId: media.id, title: text(m.title, 'title', 160), description: text(m.description, 'description', 65535), currency: currency(m.currency), priceMinor: money(m.priceMinor, 'priceMinor'), status: 'draft' }; return fromRow<PrintEdition>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: owner, recordType: 'edition', status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async transitionEdition(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'draft' | 'sellable' | 'withdrawn' }): Promise<PrintEdition> {
    if (m.status !== 'sellable') return this.transition(actor, m, 'edition', { draft: ['sellable'], sellable: ['withdrawn'], withdrawn: [] }, true);
    const owner = this.owner(actor);
    return this.mutate(actor, m, 'edition:transition', async transaction => {
      const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'edition');
      if (row.ownerUserId !== owner) throw new TrailsSyncInputError('资源不属于当前账号');
      if (m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      if (row.status !== 'draft') throw new TrailsSyncInputError('当前状态不允许该转换');
      const mediaId = text(parsed(row).mediaId, 'mediaId', 160);
      const media = await this.load(transaction, actor.tenantId, mediaId, 'media');
      if (media.ownerUserId !== owner || media.status !== 'published') throw new TrailsSyncInputError('只有已发布的父媒体可以使版次可售');
      const next: Row = { ...row, status: 'sellable', payloadJson: JSON.stringify({ ...parsed(row), status: 'sellable' }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() };
      const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction });
      if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期');
      return fromRow<PrintEdition>(saved);
    });
  }
  async inquireCommercial(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string; message: string }): Promise<CommercialLicenseInquiry> { return this.buyerCreate(actor, m, 'inquiry', { mediaId: text(m.mediaId, 'mediaId', 160), message: text(m.message, 'message', 4000), status: 'submitted' }); }
  async requestDownloadLicense(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string }): Promise<DownloadLicenseRequest> { return this.buyerCreate(actor, m, 'request', { mediaId: text(m.mediaId, 'mediaId', 160), status: 'requested' }); }
  private async buyerCreate<T>(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId: string }, type: 'inquiry' | 'request', payload: Record<string, unknown>): Promise<T> { return this.mutate(actor, m, `${type}:create`, async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const media = await this.load(transaction, actor.tenantId, text(m.mediaId, 'mediaId', 160), 'media'); if (media.status !== 'published') throw new TrailsSyncInputError('媒体不可请求'); const time = this.now(); return fromRow<T>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: media.ownerUserId, buyerUserId: actor.userId, recordType: type, status: String(payload.status), resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async decideDownloadLicense(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'granted' | 'declined' | 'revoked' }): Promise<DownloadLicenseRequest> { const owner = this.owner(actor); return this.mutate(actor, m, 'request:decide', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'request'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); const transitions: Record<string, string[]> = { requested: ['granted', 'declined'], granted: ['revoked'], declined: [], revoked: [] }; if (!transitions[row.status]?.includes(m.status)) throw new TrailsSyncInputError('当前状态不允许该转换'); const content = parsed(row); let entitlementId: string | undefined = typeof content.entitlementId === 'string' ? content.entitlementId : undefined; if (m.status === 'granted') { entitlementId = `entitlement_${row.id}`; const time = this.now(); await this.records.create({ tenantId: row.tenantId, id: entitlementId, ownerUserId: row.ownerUserId, buyerUserId: row.buyerUserId, recordType: 'entitlement', status: 'active', resourceVersion: '1', payloadJson: JSON.stringify({ mediaId: content.mediaId, requestId: row.id, status: 'active' }), createdAt: time, updatedAt: time }, { transaction }); } if (m.status === 'revoked' && entitlementId) { const entitlement = await this.load(transaction, actor.tenantId, entitlementId, 'entitlement'); await this.records.cas({ tenantId: actor.tenantId, id: entitlement.id, expectedVersion: entitlement.resourceVersion, next: { ...entitlement, status: 'revoked', payloadJson: JSON.stringify({ ...parsed(entitlement), status: 'revoked' }), resourceVersion: (BigInt(entitlement.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() } }, { transaction }); } const next: Row = { ...row, status: m.status, payloadJson: JSON.stringify({ ...content, status: m.status, ...(entitlementId ? { entitlementId } : {}) }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); return fromRow<DownloadLicenseRequest>(saved); }); }
  async createOrder(actor: Actor, m: DurableCommerceMutation & { id: string; editionId: string }): Promise<ManualOrder> { return this.mutate(actor, m, 'order:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新资源必须使用null版本'); const edition = await this.load(transaction, actor.tenantId, text(m.editionId, 'editionId', 160), 'edition'); if (edition.status !== 'sellable') throw new TrailsSyncInputError('版本不可销售'); const value = parsed(edition); const time = this.now(); const payload = { editionId: edition.id, titleSnapshot: value.title, currencySnapshot: value.currency, priceMinorSnapshot: value.priceMinor, status: 'submitted', paidMinor: 0, refundedMinor: 0 }; return fromRow<ManualOrder>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, 'id', 160), ownerUserId: edition.ownerUserId, buyerUserId: actor.userId, recordType: 'order', status: 'submitted', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); }); }
  async transitionOrder(actor: Actor, m: DurableCommerceMutation & { id: string; status: 'submitted' | 'payment-recorded' | 'fulfilled' | 'refunded' | 'cancelled'; refundMinor?: number }): Promise<ManualOrder> { const owner = this.owner(actor); return this.mutate(actor, m, 'order:transition', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, 'id', 160), 'order'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); const allowed: Record<string, string[]> = { submitted: ['payment-recorded', 'cancelled'], 'payment-recorded': ['fulfilled', 'refunded'], fulfilled: ['refunded'], refunded: [], cancelled: [] }; if (!allowed[row.status]?.includes(m.status)) throw new TrailsSyncInputError('当前状态不允许该转换'); const value = parsed(row); const paidMinor = m.status === 'payment-recorded' ? Number(value.priceMinorSnapshot) : Number(value.paidMinor); const refundedMinor = m.status === 'refunded' ? money(m.refundMinor, 'refundMinor') : Number(value.refundedMinor); if (refundedMinor > paidMinor) throw new TrailsSyncInputError('退款不能超过已记录付款'); const next: Row = { ...row, status: m.status, payloadJson: JSON.stringify({ ...value, status: m.status, paidMinor, refundedMinor }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('资源版本已过期'); return fromRow<ManualOrder>(saved); }); }
  private salesConfigurationId(ownerUserId: string): string { return `sales-configuration_${ownerUserId}`; }
  private defaultSalesConfiguration(actor: Actor, ownerUserId: string): SalesConfiguration { const time = new Date(0).toISOString(); return { id: this.salesConfigurationId(ownerUserId), tenantId: actor.tenantId, ownerUserId, salesMode: 'disabled', currency: 'CNY', reservationHours: 48, resourceVersion: '0', createdAt: time, updatedAt: time }; }
  private async salesConfiguration(transaction: TrailsSyncTransaction, actor: Actor, ownerUserId: string): Promise<SalesConfiguration> { const row = await this.records.find({ tenantId: actor.tenantId, id: this.salesConfigurationId(ownerUserId) }, { transaction }); return row && row.recordType === 'sales-configuration' ? fromRow<SalesConfiguration>(row) : this.defaultSalesConfiguration(actor, ownerUserId); }
  async readSalesWorkspace(actor: Actor): Promise<SalesWorkspace> {
    const owner = this.owner(actor);
    return this.connection.transaction(async transaction => {
      const configuration = await this.salesConfiguration(transaction, actor, owner);
      const products = (await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType: 'sales-product' }, { transaction })).map(row => fromRow<SalesProduct>(row));
      const orders = (await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType: 'sales-order' }, { transaction })).map(row => fromRow<ManualSalesOrder>(row));
      return { configuration, products, orders };
    });
  }
  async saveSalesConfiguration(actor: Actor, m: DurableCommerceMutation & { salesMode: Exclude<SalesMode, 'provider-checkout'>; currency: string; reservationHours: number }): Promise<SalesConfiguration> {
    const owner = this.owner(actor);
    if (salesMode(m.salesMode) === 'provider-checkout') throw new TrailsSyncInputError('线上支付尚未完成服务商验收，不能启用');
    const normalizedCurrency = currency(m.currency); const reservationHours = positiveInteger(m.reservationHours, '库存锁定小时数', 168);
    return this.mutate(actor, m, 'sales-configuration:save', async transaction => {
      const id = this.salesConfigurationId(owner); const prior = await this.records.find({ tenantId: actor.tenantId, id }, { transaction }); const time = this.now();
      if (!prior) {
        if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新销售配置必须使用null版本');
        return fromRow<SalesConfiguration>(await this.records.create({ tenantId: actor.tenantId, id, ownerUserId: owner, recordType: 'sales-configuration', status: m.salesMode, resourceVersion: '1', payloadJson: JSON.stringify({ salesMode: m.salesMode, currency: normalizedCurrency, reservationHours }), createdAt: time, updatedAt: time }, { transaction }));
      }
      if (prior.recordType !== 'sales-configuration' || prior.ownerUserId !== owner || m.expectedResourceVersion !== prior.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('销售配置版本已过期');
      const next: Row = { ...prior, status: m.salesMode, payloadJson: JSON.stringify({ salesMode: m.salesMode, currency: normalizedCurrency, reservationHours }), resourceVersion: (BigInt(prior.resourceVersion) + BigInt(1)).toString(), updatedAt: time };
      const saved = await this.records.cas({ tenantId: actor.tenantId, id, expectedVersion: prior.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('销售配置版本已过期'); return fromRow<SalesConfiguration>(saved);
    });
  }
  private salesProductPayload(m: { mediaId?: string; productType: SalesProductType; title: string; description: string; productionLeadDays: number; editionSize?: number; certificateIncluded: boolean; skus: SalesProductSku[] }) {
    if (m.mediaId !== undefined && !/^[A-Za-z0-9_-]{1,160}$/.test(m.mediaId)) throw new TrailsSyncInputError('关联媒体编号无效');
    if (typeof m.certificateIncluded !== 'boolean') throw new TrailsSyncInputError('作品证书标记无效');
    const editionSize = m.editionSize === undefined ? undefined : positiveInteger(m.editionSize, '限量版数量', 100_000);
    return { ...(m.mediaId ? { mediaId: m.mediaId } : {}), productType: salesProductType(m.productType), title: text(m.title, '商品标题', 160), description: text(m.description, '商品说明', 65535), productionLeadDays: positiveInteger(m.productionLeadDays, '制作周期', 365), ...(editionSize ? { editionSize } : {}), certificateIncluded: m.certificateIncluded, skus: salesSkus(m.skus), status: 'draft' as const };
  }
  async createSalesProduct(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId?: string; productType: SalesProductType; title: string; description: string; productionLeadDays: number; editionSize?: number; certificateIncluded: boolean; skus: SalesProductSku[] }): Promise<SalesProduct> {
    const owner = this.owner(actor); const payload = this.salesProductPayload(m);
    return this.mutate(actor, m, 'sales-product:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新商品必须使用null版本'); if (payload.mediaId) { const media = await this.load(transaction, actor.tenantId, payload.mediaId, 'media'); if (media.ownerUserId !== owner) throw new TrailsSyncInputError('关联媒体不属于当前创作空间'); } const time = this.now(); return fromRow<SalesProduct>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, '商品编号', 160), ownerUserId: owner, recordType: 'sales-product', status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); });
  }
  async updateSalesProduct(actor: Actor, m: DurableCommerceMutation & { id: string; mediaId?: string; productType: SalesProductType; title: string; description: string; productionLeadDays: number; editionSize?: number; certificateIncluded: boolean; skus: SalesProductSku[] }): Promise<SalesProduct> {
    const owner = this.owner(actor); const payload = this.salesProductPayload(m);
    return this.mutate(actor, m, 'sales-product:update', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, '商品编号', 160), 'sales-product'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('商品版本已过期'); if (row.status !== 'draft') throw new TrailsSyncInputError('仅草稿商品可以编辑；请先归档后重新创建'); if (payload.mediaId) { const media = await this.load(transaction, actor.tenantId, payload.mediaId, 'media'); if (media.ownerUserId !== owner) throw new TrailsSyncInputError('关联媒体不属于当前创作空间'); } const next: Row = { ...row, payloadJson: JSON.stringify(payload), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('商品版本已过期'); return fromRow<SalesProduct>(saved); });
  }
  async transitionSalesProduct(actor: Actor, m: DurableCommerceMutation & { id: string; status: SalesProductStatus }): Promise<SalesProduct> {
    const owner = this.owner(actor); const nextStatus = salesProductStatus(m.status);
    return this.mutate(actor, m, 'sales-product:transition', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, '商品编号', 160), 'sales-product'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('商品版本已过期'); const value = parsed(row); if (!((row.status === 'draft' && (nextStatus === 'ready' || nextStatus === 'archived')) || (row.status === 'ready' && nextStatus === 'archived'))) throw new TrailsSyncInputError('当前商品状态不允许该转换'); if (nextStatus === 'ready' && typeof value.mediaId === 'string') { const media = await this.load(transaction, actor.tenantId, value.mediaId, 'media'); if (media.ownerUserId !== owner || media.status !== 'published') throw new TrailsSyncInputError('商品就绪前必须发布关联媒体'); } const next: Row = { ...row, status: nextStatus, payloadJson: JSON.stringify({ ...value, status: nextStatus }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('商品版本已过期'); return fromRow<SalesProduct>(saved); });
  }
  async createManualSalesOrder(actor: Actor, m: DurableCommerceMutation & { id: string; productId: string; skuId: string; quantity: number }): Promise<ManualSalesOrder> {
    const owner = this.owner(actor); const quantity = positiveInteger(m.quantity, '购买数量', 50);
    return this.mutate(actor, m, 'sales-order:create', async transaction => { if (m.expectedResourceVersion !== null) throw new TrailsSyncInputError('新人工订单必须使用null版本'); const configuration = await this.salesConfiguration(transaction, actor, owner); if (configuration.salesMode !== 'manual') throw new TrailsSyncInputError('当前未开启人工订单模式'); const product = await this.load(transaction, actor.tenantId, text(m.productId, '商品编号', 160), 'sales-product'); if (product.ownerUserId !== owner || product.status !== 'ready') throw new TrailsSyncInputError('商品当前不可创建人工订单'); const productValue = fromRow<SalesProduct>(product); const sku = productValue.skus.find(item => item.id === text(m.skuId, '规格编号', 64)); if (!sku) throw new TrailsSyncInputError('商品规格不存在'); const time = this.now(); const existing = await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType: 'sales-order' }, { transaction }); const reserved = existing.map(row => fromRow<ManualSalesOrder>(row)).filter(order => order.productId === product.id && order.skuId === sku.id && order.status !== 'cancelled' && !(order.status === 'awaiting-payment' && new Date(order.reservationExpiresAt).getTime() <= time.getTime())).reduce((sum, order) => sum + order.quantity, 0); if (sku.inventoryMode === 'finite' && reserved + quantity > (sku.stockQuantity || 0)) throw new TrailsSyncInputError('库存不足，无法锁定此订单'); const reservationExpiresAt = new Date(time.getTime() + configuration.reservationHours * 60 * 60 * 1000).toISOString(); const payload = { productId: product.id, skuId: sku.id, quantity, titleSnapshot: productValue.title, skuLabelSnapshot: sku.label, currencySnapshot: configuration.currency, unitPriceMinorSnapshot: sku.priceMinor, totalPriceMinorSnapshot: sku.priceMinor * quantity, reservationExpiresAt, status: 'awaiting-payment' }; return fromRow<ManualSalesOrder>(await this.records.create({ tenantId: actor.tenantId, id: text(m.id, '订单编号', 160), ownerUserId: owner, recordType: 'sales-order', status: 'awaiting-payment', resourceVersion: '1', payloadJson: JSON.stringify(payload), createdAt: time, updatedAt: time }, { transaction })); });
  }
  async transitionManualSalesOrder(actor: Actor, m: DurableCommerceMutation & { id: string; status: ManualSalesOrderStatus; trackingReference?: string }): Promise<ManualSalesOrder> {
    const owner = this.owner(actor); const nextStatus = manualSalesOrderStatus(m.status); const trackingReference = optionalText(m.trackingReference, '配送参考号', 160);
    return this.mutate(actor, m, 'sales-order:transition', async transaction => { const row = await this.load(transaction, actor.tenantId, text(m.id, '订单编号', 160), 'sales-order'); if (row.ownerUserId !== owner || m.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableMediaCommerceStaleVersionError('人工订单版本已过期'); const transitions: Record<ManualSalesOrderStatus, ManualSalesOrderStatus[]> = { 'awaiting-payment': ['payment-confirmed', 'cancelled'], 'payment-confirmed': ['in-production', 'refund-pending'], 'in-production': ['shipped', 'refund-pending'], shipped: ['completed', 'refund-pending'], completed: ['refund-pending'], cancelled: [], 'refund-pending': ['refunded'], refunded: [] }; if (!transitions[row.status as ManualSalesOrderStatus]?.includes(nextStatus)) throw new TrailsSyncInputError('当前人工订单状态不允许该转换'); const value = fromRow<ManualSalesOrder>(row); const time = this.now(); if (nextStatus === 'payment-confirmed' && new Date(value.reservationExpiresAt).getTime() < time.getTime()) throw new TrailsSyncInputError('库存锁定已到期，请取消该订单后重新确认库存'); if (nextStatus === 'shipped' && !trackingReference) throw new TrailsSyncInputError('发货必须填写配送参考号'); if (trackingReference && nextStatus !== 'shipped') throw new TrailsSyncInputError('配送参考号只能在发货时填写'); const next: Row = { ...row, status: nextStatus, payloadJson: JSON.stringify({ ...parsed(row), status: nextStatus, ...(nextStatus === 'shipped' ? { shippedAt: time.toISOString(), trackingReference } : {}) }), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: time }; const saved = await this.records.cas({ tenantId: actor.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurableMediaCommerceStaleVersionError('人工订单版本已过期'); return fromRow<ManualSalesOrder>(saved); });
  }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>) { return this.connection.transaction(async transaction => { const media = (await this.records.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, recordType: 'media', status: 'published' }, { transaction })).map(row => fromRow<DurableMedia>(row)); const ids = new Set(media.map(x => x.id)); const editions = (await this.records.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, recordType: 'edition', status: 'sellable' }, { transaction })).map(row => fromRow<PrintEdition>(row)).filter(x => ids.has(x.mediaId)); return { media, editions }; }); }
  async listBuyer(actor: Actor) { return this.connection.transaction(async transaction => { const list = async <T>(recordType: RecordType) => (await this.records.list({ tenantId: actor.tenantId, buyerUserId: actor.userId, recordType }, { transaction })).map(row => fromRow<T>(row)); return { inquiries: await list<CommercialLicenseInquiry>('inquiry'), requests: await list<DownloadLicenseRequest>('request'), entitlements: await list<DownloadEntitlement>('entitlement'), orders: await list<ManualOrder>('order') }; }); }
  async listOwner(actor: Actor) { const owner = this.owner(actor); return this.connection.transaction(async transaction => { const list = async <T>(recordType: RecordType) => (await this.records.list({ tenantId: actor.tenantId, ownerUserId: owner, recordType }, { transaction })).map(row => fromRow<T>(row)); return { media: await list<DurableMedia>('media'), editions: await list<PrintEdition>('edition'), inquiries: await list<CommercialLicenseInquiry>('inquiry'), requests: await list<DownloadLicenseRequest>('request'), entitlements: await list<DownloadEntitlement>('entitlement'), orders: await list<ManualOrder>('order') }; }); }
}
const row = (attributes: ITrailsDurableMediaCommerceTableAttributes): Row => { if (!attributes.createdAt || !attributes.updatedAt) throw new TrailsSyncPersistenceError('commerce row invalid'); return { ...attributes, resourceVersion: databaseVersion(attributes.resourceVersion), createdAt: attributes.createdAt, updatedAt: attributes.updatedAt }; };
export const createSequelizeDurableMediaCommerceModels = (records: ModelStatic<TrailsDurableMediaCommerceTable>, mutations: ModelStatic<TrailsDurableMediaCommerceMutationTable>): { records: CommerceModel; mutations: CommerceMutationModel } => ({ records: { async create(input, o) { return row((await records.create(input, { transaction: sequelizeTransaction(o.transaction) })).get()); }, async find(input, o) { const tx = sequelizeTransaction(o.transaction); const found = await records.findOne({ where: input, transaction: tx, lock: tx.LOCK.UPDATE }); return found ? row(found.get()) : undefined; }, async list(input, o) { return (await records.findAll({ where: input, order: [['createdAt', 'ASC'], ['id', 'ASC']], transaction: sequelizeTransaction(o.transaction) })).map(found => row(found.get())); }, async cas(input, o) { const tx = sequelizeTransaction(o.transaction); const [affected] = await records.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction: tx }); return affected === 1 ? input.next : undefined; } }, mutations: { async find(input, o) { const tx = sequelizeTransaction(o.transaction); const found = await mutations.findOne({ where: input, transaction: tx, lock: tx.LOCK.UPDATE }); return found?.get(); }, async create(input, o) { await mutations.create(input, { transaction: sequelizeTransaction(o.transaction) }); } } });
