import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsDurableLocationCardTableAttributes, TrailsDurableLocationCardTable } from '../../../../db/mysql/models/trailsDurableLocationCard';
import { ITrailsDurableLocationCardMutationTableAttributes, TrailsDurableLocationCardMutationTable } from '../../../../db/mysql/models/trailsDurableLocationCardMutation';
import { ITrailsDurableLocationCardAuditTableAttributes, TrailsDurableLocationCardAuditTable } from '../../../../db/mysql/models/trailsDurableLocationCardAudit';
import { Actor, DurableLocationCard, DurableLocationCardDraftInput, DurableLocationCardMutation, DurableLocationCardStatus, DurableLocationCardStore } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type Row = Omit<ITrailsDurableLocationCardTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type Options = { transaction: TrailsSyncTransaction };
const sensitiveText = /https?:\/\/|www\.|\b(?:latitude|longitude|coordinates?|geometry|geohash|plus\s*code|map|route|directions?|meeting|access|parking|capacity|registration|registrations|media\s*url|operational\s*notes?)\b|(?:经纬度|坐标|几何|路线|导航|集合(?:点)?|会合(?:点)?|入口|停车|容量|名额|报名|登记|媒体链接|运营备注)/i;
const coordinateText = /[-+]?\d{1,2}(?:\.\d{3,})?\s*[,，]\s*[-+]?\d{1,3}(?:\.\d{3,})?|\b[NS]\s*\d{1,2}(?:\.\d+)?\s*[EW]\s*\d{1,3}(?:\.\d+)?\b/i;
const safeText = (value: unknown, label: string, maximum: number, optional = false): string | undefined => {
  if (value === undefined && optional) return undefined;
  if (typeof value !== 'string') throw new TrailsSyncInputError(`${label}无效`);
  const result = value.trim();
  if (!result || result.length > maximum || /[<>]|[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(result) || sensitiveText.test(result) || coordinateText.test(result)) throw new TrailsSyncInputError(`${label}包含不允许的位置或运营信息`);
  return result;
};
const opaque = (value: unknown, label: string) => { const result = safeText(value, label, 160) as string; if (!/^[A-Za-z0-9_-]+$/.test(result)) throw new TrailsSyncInputError(`${label}必须是安全不透明标识`); return result; };
const decimal = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError(`${label}必须是规范十进制字符串`); return value; };
const version = (value: unknown) => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : typeof value === 'number' && Number.isSafeInteger(value) ? String(value) : typeof value === 'bigint' ? value.toString() : (() => { throw new TrailsSyncPersistenceError('地点卡片版本无效'); })();
const payload = (value: Record<string, unknown>): DurableLocationCardDraftInput => {
  if (!Object.keys(value).every(key => ['id', 'name', 'regionLabel', 'summary'].includes(key))) throw new TrailsSyncInputError('地点卡片包含不允许字段');
  return { id: opaque(value.id, 'id'), name: safeText(value.name, 'name', 160) as string, regionLabel: safeText(value.regionLabel, 'regionLabel', 240) as string, ...(value.summary === undefined ? {} : { summary: safeText(value.summary, 'summary', 2000, true) as string }) };
};
const draftInput = (value: DurableLocationCardMutation & DurableLocationCardDraftInput) => {
  if (!Object.keys(value as object).every(key => ['id', 'name', 'regionLabel', 'summary', 'mutationId', 'expectedResourceVersion'].includes(key))) throw new TrailsSyncInputError('地点卡片包含不允许字段');
  return payload({ id: value.id, name: value.name, regionLabel: value.regionLabel, ...(value.summary === undefined ? {} : { summary: value.summary }) });
};
const readPayload = (row: Row) => { try { const value = JSON.parse(row.payloadJson) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return payload({ ...(value as Record<string, unknown>), id: row.id }); } catch (error) { if (error instanceof TrailsSyncInputError) throw error; throw new TrailsSyncPersistenceError('地点卡片载荷无效'); } };
const fromRow = (row: Row): DurableLocationCard => ({ ...readPayload(row), tenantId: row.tenantId, ownerUserId: row.ownerUserId, status: row.status as DurableLocationCardStatus, resourceVersion: version(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), ...(row.publishedAt ? { publishedAt: row.publishedAt.toISOString() } : {}), ...(row.archivedAt ? { archivedAt: row.archivedAt.toISOString() } : {}) });
export class TrailsDurableLocationCardStaleVersionError extends Error { constructor(public readonly current: DurableLocationCard) { super('地点卡片版本已过期'); } }
export interface LocationCardModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId: string; status?: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface LocationCardMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<ITrailsDurableLocationCardMutationTableAttributes | undefined>; create(row: ITrailsDurableLocationCardMutationTableAttributes, options: Options): Promise<void>; }
export interface LocationCardAuditModel { create(row: ITrailsDurableLocationCardAuditTableAttributes, options: Options): Promise<void>; }
export class MySqlDurableLocationCardRepository implements DurableLocationCardStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly cards: LocationCardModel, private readonly mutations: LocationCardMutationModel, private readonly audits: LocationCardAuditModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor) { const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return owner; }
  private async mutation<T>(actor: Actor, input: DurableLocationCardMutation, operation: string, work: (tx: TrailsSyncTransaction) => Promise<T>) { const mutationId = opaque(input.mutationId, 'mutationId'); if (input.expectedResourceVersion !== null) decimal(input.expectedResourceVersion, 'expectedResourceVersion'); const fingerprint = createHash('sha256').update(JSON.stringify({ operation, input })).digest('hex'); return this.connection.transaction(async transaction => { const prior = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId }, { transaction }); if (prior) { if (prior.fingerprint !== fingerprint) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(prior.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId, fingerprint, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async row(actor: Actor, id: string, tx: TrailsSyncTransaction) { const row = await this.cards.find({ tenantId: actor.tenantId, id: opaque(id, 'id') }, { transaction: tx }); if (!row || row.ownerUserId !== this.owner(actor)) throw new TrailsSyncInputError('地点卡片不存在或不属于当前创作空间'); return row; }
  private async audit(actor: Actor, row: Row, mutationId: string, operation: string, fromVersion: string | undefined, tx: TrailsSyncTransaction) { await this.audits.create({ eventId: `location-card-audit_${createHash('sha256').update(`${actor.tenantId}:${actor.userId}:${mutationId}`).digest('hex')}`, tenantId: row.tenantId, locationCardId: row.id, actorUserId: actor.userId, ownerUserId: row.ownerUserId, mutationId, operation, ...(fromVersion ? { fromVersion } : {}), toVersion: version(row.resourceVersion), occurredAt: row.updatedAt }, { transaction: tx }); }
  async createDraft(actor: Actor, input: DurableLocationCardMutation & DurableLocationCardDraftInput) { return this.mutation(actor, input, 'create-draft', async tx => { if (input.expectedResourceVersion !== null) throw new TrailsSyncInputError('新地点卡片必须使用null版本'); const values = draftInput(input); const time = this.now(); const row: Row = { tenantId: actor.tenantId, id: values.id, ownerUserId: this.owner(actor), status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify({ name: values.name, regionLabel: values.regionLabel, ...(values.summary ? { summary: values.summary } : {}) }), createdAt: time, updatedAt: time }; const saved = await this.cards.create(row, { transaction: tx }); await this.audit(actor, saved, input.mutationId, 'create-draft', undefined, tx); return fromRow(saved); }); }
  async updateDraft(actor: Actor, input: DurableLocationCardMutation & DurableLocationCardDraftInput) { return this.change(actor, input, 'update-draft', 'draft', () => { const values = draftInput(input); return { payloadJson: JSON.stringify({ name: values.name, regionLabel: values.regionLabel, ...(values.summary ? { summary: values.summary } : {}) }) }; }); }
  async publish(actor: Actor, input: DurableLocationCardMutation & { id: string }) { return this.change(actor, input, 'publish', 'draft', () => ({ status: 'published', publishedAt: this.now() })); }
  async unpublish(actor: Actor, input: DurableLocationCardMutation & { id: string }) { return this.change(actor, input, 'unpublish', 'published', () => ({ status: 'draft', publishedAt: undefined })); }
  async archive(actor: Actor, input: DurableLocationCardMutation & { id: string }) { return this.change(actor, input, 'archive', undefined, () => ({ status: 'archived', archivedAt: this.now() })); }
  private async change(actor: Actor, input: DurableLocationCardMutation & { id: string }, operation: string, required: DurableLocationCardStatus | undefined, patch: (row: Row) => Partial<Row>) { return this.mutation(actor, input, operation, async tx => { const row = await this.row(actor, input.id, tx); if (input.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableLocationCardStaleVersionError(fromRow(row)); if (row.status === 'archived' || (required && row.status !== required)) throw new TrailsSyncInputError('当前地点卡片不允许该操作'); const next: Row = { ...row, ...patch(row), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.cards.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction: tx }); if (!saved) throw new TrailsDurableLocationCardStaleVersionError(fromRow(await this.row(actor, input.id, tx))); await this.audit(actor, saved, input.mutationId, operation, row.resourceVersion, tx); return fromRow(saved); }); }
  async listWorkspace(actor: Actor) { return this.connection.transaction(async tx => (await this.cards.list({ tenantId: actor.tenantId, ownerUserId: this.owner(actor) }, { transaction: tx })).map(fromRow)); }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>) { return this.connection.transaction(async tx => (await this.cards.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, status: 'published' }, { transaction: tx })).map(fromRow).sort((left, right) => left.name.localeCompare(right.name) || left.id.localeCompare(right.id))); }
}
const row = (value: ITrailsDurableLocationCardTableAttributes): Row => { if (!value.createdAt || !value.updatedAt) throw new TrailsSyncPersistenceError('地点卡片行无效'); return { ...value, resourceVersion: version(value.resourceVersion), createdAt: value.createdAt, updatedAt: value.updatedAt }; };
const tx = (value: TrailsSyncTransaction) => { if (!(value instanceof Transaction)) throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); return value; };
export const createSequelizeDurableLocationCardModels = (cards: ModelStatic<TrailsDurableLocationCardTable>, mutations: ModelStatic<TrailsDurableLocationCardMutationTable>, audits: ModelStatic<TrailsDurableLocationCardAuditTable>): { cards: LocationCardModel; mutations: LocationCardMutationModel; audits: LocationCardAuditModel } => ({ cards: { async create(input, options) { return row((await cards.create(input, { transaction: tx(options.transaction) })).get()); }, async find(input, options) { const transaction = tx(options.transaction); const value = await cards.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return value ? row(value.get()) : undefined; }, async list(input, options) { return (await cards.findAll({ where: input, order: [['payloadJson', 'ASC'], ['id', 'ASC']], transaction: tx(options.transaction) })).map(value => row(value.get())); }, async cas(input, options) { const [changed] = await cards.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction: tx(options.transaction) }); return changed === 1 ? input.next : undefined; } }, mutations: { async find(input, options) { const transaction = tx(options.transaction); return (await mutations.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }))?.get(); }, async create(input, options) { await mutations.create(input, { transaction: tx(options.transaction) }); } }, audits: { async create(input, options) { await audits.create(input, { transaction: tx(options.transaction) }); } } });
