import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsDurablePublishingPackageAuditTableAttributes, TrailsDurablePublishingPackageAuditTable } from '../../../../db/mysql/models/trailsDurablePublishingPackageAudit';
import { ITrailsDurablePublishingPackageMutationTableAttributes, TrailsDurablePublishingPackageMutationTable } from '../../../../db/mysql/models/trailsDurablePublishingPackageMutation';
import { ITrailsDurablePublishingPackageTableAttributes, TrailsDurablePublishingPackageTable } from '../../../../db/mysql/models/trailsDurablePublishingPackage';
import { Actor, DurablePublishingLearning, DurablePublishingMeasurementEvent, DurablePublishingMutation, DurablePublishingPackage, DurablePublishingPackageStatus, DurablePublishingPackageStore } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type Row = Omit<ITrailsDurablePublishingPackageTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type MutationRow = ITrailsDurablePublishingPackageMutationTableAttributes;
type AuditRow = ITrailsDurablePublishingPackageAuditTableAttributes;
type Options = { transaction: TrailsSyncTransaction };
export class TrailsDurablePublishingPackageStaleVersionError extends Error {}
const statusGraph: Record<DurablePublishingPackageStatus, DurablePublishingPackageStatus[]> = { draft: ['prepared'], prepared: ['reviewed'], reviewed: ['approved'], approved: ['ready_manual_handoff'], ready_manual_handoff: ['manually_published'], manually_published: ['measured'], measured: ['learned'], learned: [] };
const text = (value: unknown, label: string, max: number): string => { if (typeof value !== 'string' || !value.trim() || value.length > max) throw new TrailsSyncInputError(`${label}无效`); return value.trim(); };
const opaque = (value: unknown, label: string) => { const result = text(value, label, 160); if (!/^[A-Za-z0-9_-]+$/.test(result)) throw new TrailsSyncInputError(`${label}必须是安全不透明标识`); return result; };
const decimal = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError(`${label}必须是规范十进制字符串`); return value; };
const version = (value: unknown): string => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : typeof value === 'number' && Number.isSafeInteger(value) ? String(value) : typeof value === 'bigint' ? value.toString() : (() => { throw new TrailsSyncPersistenceError('发布包版本无效'); })();
const fingerprint = (operation: string, input: unknown) => createHash('sha256').update(JSON.stringify({ operation, input })).digest('hex');
const sequelizeTransaction = (tx: TrailsSyncTransaction) => { if (!(tx instanceof Transaction)) throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); return tx; };
const parsePayload = (row: Row): Record<string, unknown> => { try { const value = JSON.parse(row.payloadJson) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return value as Record<string, unknown>; } catch { throw new TrailsSyncPersistenceError('发布包载荷无效'); } };
const fromRow = (row: Row): DurablePublishingPackage => ({ ...parsePayload(row), id: row.id, tenantId: row.tenantId, ownerUserId: row.ownerUserId, status: row.status as DurablePublishingPackageStatus, resourceVersion: version(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as DurablePublishingPackage);
const validMeasurements = (items: unknown): DurablePublishingMeasurementEvent[] => { if (!Array.isArray(items) || items.length < 1 || items.length > 100) throw new TrailsSyncInputError('measurementEvents必须是1至100项数组'); return items.map((item, index) => { if (!item || typeof item !== 'object' || Array.isArray(item)) throw new TrailsSyncInputError(`measurementEvents[${index}]无效`); const value = item as Record<string, unknown>; const occurredAt = text(value.occurredAt, `measurementEvents[${index}].occurredAt`, 32); if (new Date(occurredAt).toISOString() !== occurredAt) throw new TrailsSyncInputError(`measurementEvents[${index}].occurredAt必须是规范UTC ISO时间`); if (!['impressions', 'reach', 'engagements', 'profile_visits', 'link_clicks', 'qualified_inquiries'].includes(String(value.metric)) || typeof value.value !== 'number' || !Number.isFinite(value.value) || value.value < 0) throw new TrailsSyncInputError(`measurementEvents[${index}]无效`); return { occurredAt, metric: value.metric as DurablePublishingMeasurementEvent['metric'], value: value.value }; }); };
const validatePayload = (value: Record<string, unknown>) => {
  const exportVariants = value.exportVariants; if (!Array.isArray(exportVariants) || exportVariants.length < 1 || exportVariants.length > 20) throw new TrailsSyncInputError('exportVariants必须是1至20项数组');
  const variants = exportVariants.map((item, index) => { if (!item || typeof item !== 'object' || Array.isArray(item)) throw new TrailsSyncInputError(`exportVariants[${index}]无效`); const x = item as Record<string, unknown>; if (!['square', 'portrait', 'landscape', 'original'].includes(String(x.cropIntent))) throw new TrailsSyncInputError(`exportVariants[${index}].cropIntent无效`); return { mediaId: opaque(x.mediaId, `exportVariants[${index}].mediaId`), cropIntent: x.cropIntent, intendedUse: text(x.intendedUse, `exportVariants[${index}].intendedUse`, 240) }; });
  if (value.contentOrigin !== 'human' && value.contentOrigin !== 'ai-draft-requires-review') throw new TrailsSyncInputError('contentOrigin无效'); if (value.locationPolicy !== 'withheld' && value.locationPolicy !== 'generalized') throw new TrailsSyncInputError('locationPolicy无效'); if (typeof value.containsGpsOrRouteHints !== 'boolean') throw new TrailsSyncInputError('containsGpsOrRouteHints必须是布尔值'); if (value.rightsStatus !== 'cleared' && value.rightsStatus !== 'restricted') throw new TrailsSyncInputError('rightsStatus无效');
  const claims = value.factualClaims; if (!Array.isArray(claims) || claims.length > 100) throw new TrailsSyncInputError('factualClaims无效'); const factualClaims = claims.map((item, index) => { if (!item || typeof item !== 'object' || Array.isArray(item)) throw new TrailsSyncInputError(`factualClaims[${index}]无效`); const x = item as Record<string, unknown>; if (x.verification !== 'verified' && x.verification !== 'unverified') throw new TrailsSyncInputError(`factualClaims[${index}].verification无效`); return { text: text(x.text, `factualClaims[${index}].text`, 1000), verification: x.verification }; });
  const approvals = value.approvals; if (!approvals || typeof approvals !== 'object' || Array.isArray(approvals) || !['copyApproved', 'mediaSelectionApproved', 'rightsApproved', 'locationPrivacyApproved', 'factualClaimsApproved'].every(key => typeof (approvals as Record<string, unknown>)[key] === 'boolean')) throw new TrailsSyncInputError('approvals无效');
  const rightsDisclosure = value.rightsDisclosure === undefined ? undefined : text(value.rightsDisclosure, 'rightsDisclosure', 4000);
  return { sourceWorkId: opaque(value.sourceWorkId, 'sourceWorkId'), platform: text(value.platform, 'platform', 80), copy: text(value.copy, 'copy', 20000), contentOrigin: value.contentOrigin, exportVariants: variants, locationPolicy: value.locationPolicy, containsGpsOrRouteHints: value.containsGpsOrRouteHints, rightsStatus: value.rightsStatus, ...(rightsDisclosure ? { rightsDisclosure } : {}), factualClaims, approvals: approvals as DurablePublishingPackage['approvals'] };
};
const approvalBlock = (item: DurablePublishingPackage) => item.locationPolicy === 'withheld' && item.containsGpsOrRouteHints ? '已隐去地点的发布包不能包含GPS或路线提示' : item.rightsStatus === 'restricted' && !item.rightsDisclosure ? '受限权利必须披露' : item.factualClaims.some(x => x.verification === 'unverified') ? '未核验事实声明不能批准' : !Object.values(item.approvals).every(Boolean) ? '必须完成五项人工批准' : undefined;
export interface PublishingPackageModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface PublishingMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<MutationRow | undefined>; create(row: MutationRow, options: Options): Promise<void>; }
export interface PublishingAuditModel { create(row: AuditRow, options: Options): Promise<void>; }
export class MySqlDurablePublishingPackageRepository implements DurablePublishingPackageStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly packages: PublishingPackageModel, private readonly mutations: PublishingMutationModel, private readonly audits: PublishingAuditModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor) { const value = creatorSpaceOwnerId(actor); if (!value) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return value; }
  private async mutate<T>(actor: Actor, mutation: DurablePublishingMutation, operation: string, work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> { text(mutation.mutationId, 'mutationId', 160); if (mutation.expectedResourceVersion !== null) decimal(mutation.expectedResourceVersion, 'expectedResourceVersion'); const digest = fingerprint(operation, mutation); return this.connection.transaction(async transaction => { const previous = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId: mutation.mutationId }, { transaction }); if (previous) { if (previous.fingerprint !== digest) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(previous.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId: mutation.mutationId, fingerprint: digest, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async row(actor: Actor, id: string, transaction: TrailsSyncTransaction) { const row = await this.packages.find({ tenantId: actor.tenantId, id: opaque(id, 'id') }, { transaction }); if (!row || row.ownerUserId !== this.owner(actor)) throw new TrailsSyncInputError('发布包不存在或不属于当前创作空间'); return row; }
  private async audit(actor: Actor, row: Row, mutationId: string, operation: string, fromStatus: string | undefined, transaction: TrailsSyncTransaction) { await this.audits.create({ eventId: `publishing-package-audit_${createHash('sha256').update(`${actor.tenantId}:${actor.userId}:${mutationId}`).digest('hex')}`, tenantId: row.tenantId, packageId: row.id, actorUserId: actor.userId, ownerUserId: row.ownerUserId, mutationId, operation, ...(fromStatus ? { fromStatus } : {}), toStatus: row.status, resourceVersion: version(row.resourceVersion), occurredAt: row.updatedAt }, { transaction }); }
  async create(actor: Actor, input: DurablePublishingMutation & Omit<DurablePublishingPackage, 'tenantId' | 'ownerUserId' | 'status' | 'manuallyPublishedByUserId' | 'manuallyPublishedAt' | 'measurementEvents' | 'learning' | 'resourceVersion' | 'createdAt' | 'updatedAt'>) { const owner = this.owner(actor); return this.mutate(actor, input, 'create', async transaction => { if (input.expectedResourceVersion !== null) throw new TrailsSyncInputError('新发布包必须使用null版本'); const time = this.now(); const row: Row = { tenantId: actor.tenantId, id: opaque(input.id, 'id'), ownerUserId: owner, platform: text(input.platform, 'platform', 80), status: 'draft', resourceVersion: '1', payloadJson: JSON.stringify({ ...validatePayload(input as unknown as Record<string, unknown>), measurementEvents: [] }), createdAt: time, updatedAt: time }; const saved = await this.packages.create(row, { transaction }); await this.audit(actor, saved, input.mutationId, 'create', undefined, transaction); return fromRow(saved); }); }
  async transition(actor: Actor, input: DurablePublishingMutation & { id: string; status: DurablePublishingPackageStatus; manualConfirmation?: boolean }) { return this.mutate(actor, input, 'transition', async transaction => { const row = await this.row(actor, input.id, transaction); if (input.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurablePublishingPackageStaleVersionError('发布包版本已过期'); const current = fromRow(row); if (!statusGraph[current.status].includes(input.status)) throw new TrailsSyncInputError('当前发布包状态不允许该转换'); if (input.status === 'approved') { const block = approvalBlock(current); if (block) throw new TrailsSyncInputError(block); } if (input.status === 'manually_published' && input.manualConfirmation !== true) throw new TrailsSyncInputError('手动发布必须由人工确认'); const time = this.now(); const payload = { ...parsePayload(row), ...(input.status === 'manually_published' ? { manuallyPublishedByUserId: actor.userId, manuallyPublishedAt: time.toISOString() } : {}) }; const next: Row = { ...row, status: input.status, resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), payloadJson: JSON.stringify(payload), updatedAt: time }; const saved = await this.packages.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurablePublishingPackageStaleVersionError('发布包版本已过期'); await this.audit(actor, saved, input.mutationId, 'transition', row.status, transaction); return fromRow(saved); }); }
  async measure(actor: Actor, input: DurablePublishingMutation & { id: string; measurementEvents: DurablePublishingMeasurementEvent[] }) { return this.update(actor, input, 'measure', 'manually_published', 'measured', { measurementEvents: validMeasurements(input.measurementEvents) }); }
  async learn(actor: Actor, input: DurablePublishingMutation & { id: string; learning: DurablePublishingLearning }) { const learning = input.learning; if (!learning || (learning.confidence !== 'low' && learning.confidence !== 'medium' && learning.confidence !== 'high')) throw new TrailsSyncInputError('learning.confidence无效'); return this.update(actor, input, 'learn', 'measured', 'learned', { learning: { summary: text(learning.summary, 'learning.summary', 4000), confidence: learning.confidence } }); }
  private async update(actor: Actor, input: DurablePublishingMutation & { id: string }, operation: 'measure' | 'learn', required: DurablePublishingPackageStatus, nextStatus: DurablePublishingPackageStatus, patch: Record<string, unknown>) { return this.mutate(actor, input, operation, async transaction => { const row = await this.row(actor, input.id, transaction); if (input.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurablePublishingPackageStaleVersionError('发布包版本已过期'); if (row.status !== required) throw new TrailsSyncInputError(`只有${required}状态的发布包可以${operation}`); const next: Row = { ...row, status: nextStatus, resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), payloadJson: JSON.stringify({ ...parsePayload(row), ...patch }), updatedAt: this.now() }; const saved = await this.packages.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsDurablePublishingPackageStaleVersionError('发布包版本已过期'); await this.audit(actor, saved, input.mutationId, operation, row.status, transaction); return fromRow(saved); }); }
  async listWorkspace(actor: Actor) { const owner = this.owner(actor); return this.connection.transaction(async transaction => (await this.packages.list({ tenantId: actor.tenantId, ownerUserId: owner }, { transaction })).map(fromRow)); }
}
const row = (x: ITrailsDurablePublishingPackageTableAttributes): Row => { if (!x.createdAt || !x.updatedAt) throw new TrailsSyncPersistenceError('发布包行无效'); return { ...x, resourceVersion: version(x.resourceVersion), createdAt: x.createdAt, updatedAt: x.updatedAt }; };
export const createSequelizeDurablePublishingPackageModels = (packages: ModelStatic<TrailsDurablePublishingPackageTable>, mutations: ModelStatic<TrailsDurablePublishingPackageMutationTable>, audits: ModelStatic<TrailsDurablePublishingPackageAuditTable>): { packages: PublishingPackageModel; mutations: PublishingMutationModel; audits: PublishingAuditModel } => ({ packages: { async create(input, o) { return row((await packages.create(input, { transaction: sequelizeTransaction(o.transaction) })).get()); }, async find(input, o) { const tx = sequelizeTransaction(o.transaction); const value = await packages.findOne({ where: input, transaction: tx, lock: tx.LOCK.UPDATE }); return value ? row(value.get()) : undefined; }, async list(input, o) { return (await packages.findAll({ where: input, order: [['createdAt', 'ASC'], ['id', 'ASC']], transaction: sequelizeTransaction(o.transaction) })).map(value => row(value.get())); }, async cas(input, o) { const [changed] = await packages.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction: sequelizeTransaction(o.transaction) }); return changed === 1 ? input.next : undefined; } }, mutations: { async find(input, o) { const tx = sequelizeTransaction(o.transaction); const value = await mutations.findOne({ where: input, transaction: tx, lock: tx.LOCK.UPDATE }); return value?.get(); }, async create(input, o) { await mutations.create(input, { transaction: sequelizeTransaction(o.transaction) }); } }, audits: { async create(input, o) { await audits.create(input, { transaction: sequelizeTransaction(o.transaction) }); } } });
