import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsShootingLocationTableAttributes, TrailsShootingLocationTable } from '../../../../db/mysql/models/trailsShootingLocation';
import { ITrailsShootingLocationMutationTableAttributes, TrailsShootingLocationMutationTable } from '../../../../db/mysql/models/trailsShootingLocationMutation';
import { ITrailsShootingLocationAuditTableAttributes, TrailsShootingLocationAuditTable } from '../../../../db/mysql/models/trailsShootingLocationAudit';
import { Actor, ShootingLocation, ShootingLocationDraftInput, ShootingLocationMutation, ShootingLocationStatus, ShootingLocationStore } from '../types';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type Row = Omit<ITrailsShootingLocationTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type Options = { transaction: TrailsSyncTransaction };
const opaque = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{1,160}$/.test(value)) throw new TrailsSyncInputError(`${label}必须是安全不透明标识`); return value; };
const text = (value: unknown, label: string, maximum: number, optional = false): string | undefined => { if (value === undefined && optional) return undefined; if (typeof value !== 'string') throw new TrailsSyncInputError(`${label}无效`); const normalized = value.trim(); if (!normalized || normalized.length > maximum || /[<>]|[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(normalized)) throw new TrailsSyncInputError(`${label}无效`); return normalized; };
const coordinate = (value: unknown, label: string, minimum: number, maximum: number) => { if (typeof value !== 'number' || !Number.isFinite(value) || value < minimum || value > maximum) throw new TrailsSyncInputError(`${label}无效`); return value; };
const decimal = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError(`${label}必须是规范十进制字符串`); return value; };
const version = (value: unknown) => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : (() => { throw new TrailsSyncPersistenceError('拍摄地点版本无效'); })();
const input = (value: Record<string, unknown>): ShootingLocationDraftInput => { if (!Object.keys(value).every(key => ['id', 'name', 'latitude', 'longitude', 'notes'].includes(key))) throw new TrailsSyncInputError('拍摄地点包含不允许字段'); return { id: opaque(value.id, 'id'), name: text(value.name, 'name', 160) as string, latitude: coordinate(value.latitude, 'latitude', -90, 90), longitude: coordinate(value.longitude, 'longitude', -180, 180), ...(value.notes === undefined ? {} : { notes: text(value.notes, 'notes', 10000, true) as string }) }; };
const mutationInput = (value: ShootingLocationMutation & ShootingLocationDraftInput) => { if (!Object.keys(value as object).every(key => ['id', 'name', 'latitude', 'longitude', 'notes', 'mutationId', 'expectedResourceVersion'].includes(key))) throw new TrailsSyncInputError('拍摄地点包含不允许字段'); return input({ id: value.id, name: value.name, latitude: value.latitude, longitude: value.longitude, ...(value.notes === undefined ? {} : { notes: value.notes }) }); };
const fromRow = (row: Row): ShootingLocation => { try { const parsed = JSON.parse(row.payloadJson); return { ...input({ ...parsed, id: row.id }), tenantId: row.tenantId, ownerUserId: row.ownerUserId, status: row.status as ShootingLocationStatus, resourceVersion: version(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), ...(row.archivedAt ? { archivedAt: row.archivedAt.toISOString() } : {}) }; } catch (error) { if (error instanceof TrailsSyncInputError) throw error; throw new TrailsSyncPersistenceError('拍摄地点载荷无效'); } };
export class TrailsShootingLocationStaleVersionError extends Error { constructor(public readonly current: ShootingLocation) { super('拍摄地点版本已过期'); } }
export interface ShootingLocationModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface ShootingLocationMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<ITrailsShootingLocationMutationTableAttributes | undefined>; create(row: ITrailsShootingLocationMutationTableAttributes, options: Options): Promise<void>; }
export interface ShootingLocationAuditModel { create(row: ITrailsShootingLocationAuditTableAttributes, options: Options): Promise<void>; }
export class MySqlShootingLocationRepository implements ShootingLocationStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly locations: ShootingLocationModel, private readonly mutations: ShootingLocationMutationModel, private readonly audits: ShootingLocationAuditModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor) { if (actor.creatorSpaceRole !== 'creator-space-owner') throw new TrailsSyncInputError('当前账号没有拍摄地点管理权限'); return actor.userId; }
  private async apply<T>(actor: Actor, value: ShootingLocationMutation, operation: string, work: (tx: TrailsSyncTransaction) => Promise<T>) { const mutationId = opaque(value.mutationId, 'mutationId'); if (value.expectedResourceVersion !== null) decimal(value.expectedResourceVersion, 'expectedResourceVersion'); const fingerprint = createHash('sha256').update(JSON.stringify({ operation, input: value })).digest('hex'); return this.connection.transaction(async transaction => { const prior = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId }, { transaction }); if (prior) { if (prior.fingerprint !== fingerprint) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(prior.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId, fingerprint, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async row(actor: Actor, id: string, transaction: TrailsSyncTransaction) { const row = await this.locations.find({ tenantId: actor.tenantId, id: opaque(id, 'id') }, { transaction }); if (!row || row.ownerUserId !== this.owner(actor)) throw new TrailsSyncInputError('拍摄地点不存在或不属于当前所有者'); return row; }
  private audit(actor: Actor, row: Row, mutationId: string, operation: string, fromVersion: string | undefined, transaction: TrailsSyncTransaction) { return this.audits.create({ eventId: `shooting-location-audit_${createHash('sha256').update(`${actor.tenantId}:${actor.userId}:${mutationId}`).digest('hex')}`, tenantId: row.tenantId, shootingLocationId: row.id, actorUserId: actor.userId, ownerUserId: row.ownerUserId, mutationId, operation, ...(fromVersion ? { fromVersion } : {}), toVersion: version(row.resourceVersion), occurredAt: row.updatedAt }, { transaction }); }
  async create(actor: Actor, value: ShootingLocationMutation & ShootingLocationDraftInput) { return this.apply(actor, value, 'create', async transaction => { if (value.expectedResourceVersion !== null) throw new TrailsSyncInputError('新拍摄地点必须使用null版本'); const payload = mutationInput(value); const time = this.now(); const saved = await this.locations.create({ tenantId: actor.tenantId, id: payload.id, ownerUserId: this.owner(actor), status: 'active', resourceVersion: '1', payloadJson: JSON.stringify({ name: payload.name, latitude: payload.latitude, longitude: payload.longitude, ...(payload.notes ? { notes: payload.notes } : {}) }), createdAt: time, updatedAt: time }, { transaction }); await this.audit(actor, saved, value.mutationId, 'create', undefined, transaction); return fromRow(saved); }); }
  async update(actor: Actor, value: ShootingLocationMutation & ShootingLocationDraftInput) { return this.change(actor, value, 'update', row => { const payload = mutationInput(value); return { ...row, payloadJson: JSON.stringify({ name: payload.name, latitude: payload.latitude, longitude: payload.longitude, ...(payload.notes ? { notes: payload.notes } : {}) }) }; }); }
  async archive(actor: Actor, value: ShootingLocationMutation & { id: string }) { return this.change(actor, value, 'archive', row => ({ ...row, status: 'archived', archivedAt: this.now() })); }
  private async change(actor: Actor, value: ShootingLocationMutation & { id: string }, operation: string, patch: (row: Row) => Row) { return this.apply(actor, value, operation, async transaction => { const row = await this.row(actor, value.id, transaction); if (value.expectedResourceVersion !== row.resourceVersion) throw new TrailsShootingLocationStaleVersionError(fromRow(row)); if (row.status !== 'active') throw new TrailsSyncInputError('当前拍摄地点不允许该操作'); const next = { ...patch(row), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.locations.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction }); if (!saved) throw new TrailsShootingLocationStaleVersionError(fromRow(await this.row(actor, value.id, transaction))); await this.audit(actor, saved, value.mutationId, operation, row.resourceVersion, transaction); return fromRow(saved); }); }
  async listWorkspace(actor: Actor) { return this.connection.transaction(async transaction => (await this.locations.list({ tenantId: actor.tenantId, ownerUserId: this.owner(actor) }, { transaction })).map(fromRow)); }
}
const row = (value: ITrailsShootingLocationTableAttributes): Row => { if (!value.createdAt || !value.updatedAt) throw new TrailsSyncPersistenceError('拍摄地点行无效'); return { ...value, resourceVersion: version(value.resourceVersion), createdAt: value.createdAt, updatedAt: value.updatedAt }; };
const tx = (value: TrailsSyncTransaction) => { if (!(value instanceof Transaction)) throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); return value; };
export const createSequelizeShootingLocationModels = (locations: ModelStatic<TrailsShootingLocationTable>, mutations: ModelStatic<TrailsShootingLocationMutationTable>, audits: ModelStatic<TrailsShootingLocationAuditTable>): { locations: ShootingLocationModel; mutations: ShootingLocationMutationModel; audits: ShootingLocationAuditModel } => ({ locations: { async create(value, options) { return row((await locations.create(value, { transaction: tx(options.transaction) })).get()); }, async find(value, options) { const transaction = tx(options.transaction); const found = await locations.findOne({ where: value, transaction, lock: transaction.LOCK.UPDATE }); return found ? row(found.get()) : undefined; }, async list(value, options) { return (await locations.findAll({ where: value, order: [['updatedAt', 'DESC'], ['id', 'ASC']], transaction: tx(options.transaction) })).map(found => row(found.get())); }, async cas(value, options) { const [changed] = await locations.update(value.next, { where: { tenantId: value.tenantId, id: value.id, resourceVersion: value.expectedVersion }, transaction: tx(options.transaction) }); return changed === 1 ? value.next : undefined; } }, mutations: { async find(value, options) { const transaction = tx(options.transaction); return (await mutations.findOne({ where: value, transaction, lock: transaction.LOCK.UPDATE }))?.get(); }, async create(value, options) { await mutations.create(value, { transaction: tx(options.transaction) }); } }, audits: { async create(value, options) { await audits.create(value, { transaction: tx(options.transaction) }); } } });
