import { ModelStatic, Order, Transaction } from 'sequelize';
import { ITrailsDurableJournalTableAttributes, TrailsDurableJournalTable } from '../../../../db/mysql/models/trailsDurableJournal';
import { Actor, DurableJournal, DurableJournalDraftInput, DurableJournalPinInput, DurableJournalStore, DurableJournalTransitionInput, DurableJournalUpdateInput } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';
import { RichDocumentPublishValidator } from './mysqlRichDocument';

type Row = Omit<ITrailsDurableJournalTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type Options = { transaction: TrailsSyncTransaction };
export class TrailsDurableJournalStaleVersionError extends Error {}
const maxUnsignedBigInt = BigInt('18446744073709551615');
export interface DurableJournalModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId: string; publicOnly?: boolean }, options: Options): Promise<Row[]>; compareAndSwap(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
const text = (value: unknown, label: string, maximum: number): string => { if (typeof value !== 'string' || !value.trim() || value.length > maximum) throw new TrailsSyncInputError(`${label}无效`); return value.trim(); };
const bodyText = (value: unknown): string => { if (typeof value !== 'string' || value.length > 65535) throw new TrailsSyncInputError('body无效'); return value; };
const optional = (value: unknown, label: string, maximum: number): string | undefined => value === undefined ? undefined : text(value, label, maximum);
const version = (value: unknown): string => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError('resourceVersion必须是规范十进制字符串'); return value; };
const fromRow = (row: Row): DurableJournal => ({ id: row.id, tenantId: row.tenantId, ownerUserId: row.ownerUserId, title: row.title, excerpt: row.excerpt, body: row.body, ...(row.coverMediaId ? { coverMediaId: row.coverMediaId } : {}), ...(row.publishedAt ? { publishedAt: row.publishedAt.toISOString() } : {}), isPinned: row.isPinned, visibility: row.visibility, lifecycle: row.lifecycle, resourceVersion: row.resourceVersion, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() });

export class MySqlDurableJournalRepository implements DurableJournalStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly journals: DurableJournalModel, private readonly now: () => Date = () => new Date(), private readonly richDocuments?: RichDocumentPublishValidator) {}
  async createDraft(actor: Actor, input: DurableJournalDraftInput): Promise<DurableJournal> {
    const ownerUserId = creatorSpaceOwnerId(actor); if (!ownerUserId) throw new TrailsSyncInputError('当前账号没有创作空间管理权限');
    const timestamp = this.now(); const row: Row = { id: text(input.id, 'id', 160), tenantId: actor.tenantId, ownerUserId, title: text(input.title, 'title', 160), excerpt: text(input.excerpt, 'excerpt', 65535), body: bodyText(input.body), coverMediaId: optional(input.coverMediaId, 'coverMediaId', 160), isPinned: false, visibility: input.visibility, lifecycle: 'draft', resourceVersion: '1', createdAt: timestamp, updatedAt: timestamp };
    if (row.visibility !== 'public' && row.visibility !== 'private' && row.visibility !== 'unlisted') throw new TrailsSyncInputError('visibility无效');
    return this.connection.transaction(async (transaction) => fromRow(await this.journals.create(row, { transaction })));
  }
  async update(actor: Actor, input: DurableJournalUpdateInput): Promise<DurableJournal> { const ownerUserId = creatorSpaceOwnerId(actor); if (!ownerUserId) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); const expectedVersion = version(input.resourceVersion); return this.connection.transaction(async transaction => { const current = await this.journals.find({ tenantId: actor.tenantId, id: text(input.id, 'id', 160) }, { transaction }); if (!current || current.ownerUserId !== ownerUserId) throw new TrailsSyncInputError('日记不属于当前创作空间'); if (current.lifecycle !== 'draft') throw new TrailsSyncInputError('只有草稿日记可以更新'); if (current.resourceVersion !== expectedVersion) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); const next = { ...current, title: text(input.title, 'title', 160), excerpt: text(input.excerpt, 'excerpt', 65535), body: bodyText(input.body), coverMediaId: optional(input.coverMediaId, 'coverMediaId', 160), visibility: input.visibility, resourceVersion: (BigInt(current.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; if (!['public', 'private', 'unlisted'].includes(next.visibility)) throw new TrailsSyncInputError('visibility无效'); const saved = await this.journals.compareAndSwap({ tenantId: actor.tenantId, id: current.id, expectedVersion, next }, { transaction }); if (!saved) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); return fromRow(saved); }); }
  async publish(actor: Actor, input: DurableJournalTransitionInput): Promise<DurableJournal> {
    const ownerUserId = creatorSpaceOwnerId(actor); if (!ownerUserId) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); const expectedVersion = version(input.resourceVersion);
    return this.connection.transaction(async (transaction) => { const current = await this.journals.find({ tenantId: actor.tenantId, id: input.id }, { transaction }); if (!current || current.ownerUserId !== ownerUserId) throw new TrailsSyncInputError('日记不属于当前创作空间'); if (current.lifecycle !== 'draft') throw new TrailsSyncInputError('只有草稿日记可以发布'); if (current.resourceVersion !== expectedVersion) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); if (!this.richDocuments) throw new TrailsSyncPersistenceError('rich document publish validator is unavailable'); await this.richDocuments.validate(transaction, { tenantId: current.tenantId, ownerUserId, subjectType: 'journal', subjectId: current.id }); if (BigInt(current.resourceVersion) >= maxUnsignedBigInt) throw new TrailsSyncInputError('日记版本已达到存储上限'); const timestamp = this.now(); const next = { ...current, lifecycle: 'published' as const, publishedAt: timestamp, resourceVersion: (BigInt(current.resourceVersion) + BigInt(1)).toString(), updatedAt: timestamp }; const saved = await this.journals.compareAndSwap({ tenantId: actor.tenantId, id: current.id, expectedVersion, next }, { transaction }); if (!saved) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); return fromRow(saved); });
  }
  async unpublish(actor: Actor, input: DurableJournalTransitionInput): Promise<DurableJournal> { const ownerUserId = creatorSpaceOwnerId(actor); if (!ownerUserId) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); const expectedVersion = version(input.resourceVersion); return this.connection.transaction(async transaction => { const current = await this.journals.find({ tenantId: actor.tenantId, id: text(input.id, 'id', 160) }, { transaction }); if (!current || current.ownerUserId !== ownerUserId) throw new TrailsSyncInputError('日记不属于当前创作空间'); if (current.lifecycle !== 'published') throw new TrailsSyncInputError('只有已发布日记可以取消发布'); if (current.resourceVersion !== expectedVersion) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); const next = { ...current, lifecycle: 'draft' as const, publishedAt: undefined, isPinned: false, resourceVersion: (BigInt(current.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.journals.compareAndSwap({ tenantId: actor.tenantId, id: current.id, expectedVersion, next }, { transaction }); if (!saved) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); return fromRow(saved); }); }
  async setPinned(actor: Actor, input: DurableJournalPinInput): Promise<DurableJournal> { const ownerUserId = creatorSpaceOwnerId(actor); if (!ownerUserId) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); const expectedVersion = version(input.resourceVersion); if (typeof input.isPinned !== 'boolean') throw new TrailsSyncInputError('isPinned无效'); return this.connection.transaction(async transaction => { const current = await this.journals.find({ tenantId: actor.tenantId, id: text(input.id, 'id', 160) }, { transaction }); if (!current || current.ownerUserId !== ownerUserId) throw new TrailsSyncInputError('日记不属于当前创作空间'); if (current.lifecycle !== 'published' || current.visibility !== 'public') throw new TrailsSyncInputError('只有公开的已发布日记可以置顶'); if (current.resourceVersion !== expectedVersion) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); const next = { ...current, isPinned: input.isPinned, resourceVersion: (BigInt(current.resourceVersion) + BigInt(1)).toString(), updatedAt: this.now() }; const saved = await this.journals.compareAndSwap({ tenantId: actor.tenantId, id: current.id, expectedVersion, next }, { transaction }); if (!saved) throw new TrailsDurableJournalStaleVersionError('日记版本已过期'); return fromRow(saved); }); }
  async listWorkspace(actor: Actor): Promise<DurableJournal[]> { const ownerUserId = creatorSpaceOwnerId(actor); if (!ownerUserId) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return this.connection.transaction(async (transaction) => (await this.journals.list({ tenantId: actor.tenantId, ownerUserId }, { transaction })).map(fromRow)); }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>): Promise<DurableJournal[]> { return this.connection.transaction(async (transaction) => (await this.journals.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, publicOnly: true }, { transaction })).map(fromRow)); }
}

const sequelizeTransaction = (transaction: TrailsSyncTransaction): Transaction => { if (transaction instanceof Transaction) return transaction; throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); };
const databaseVersion = (value: unknown): string => { if (typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value)) return value; if (typeof value === 'bigint' && value >= BigInt(0)) return value.toString(); if (typeof value === 'number' && Number.isSafeInteger(value) && value >= 0) return String(value); throw new TrailsSyncPersistenceError('journal resource version is invalid'); };
const row = (attributes: ITrailsDurableJournalTableAttributes): Row => { if (!attributes.createdAt || !attributes.updatedAt) throw new TrailsSyncPersistenceError('journal row is invalid'); return { ...attributes, resourceVersion: databaseVersion(attributes.resourceVersion), createdAt: attributes.createdAt, updatedAt: attributes.updatedAt }; };
export const createSequelizeDurableJournalModel = (model: ModelStatic<TrailsDurableJournalTable>): DurableJournalModel => ({
  async create(input, options) { return row((await model.create(input, { transaction: sequelizeTransaction(options.transaction) })).get()); },
  async find(input, options) { const transaction = sequelizeTransaction(options.transaction); const result = await model.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return result ? row(result.get()) : undefined; },
  async list(input, options) { const where = input.publicOnly ? { tenantId: input.tenantId, ownerUserId: input.ownerUserId, visibility: 'public', lifecycle: 'published' } : { tenantId: input.tenantId, ownerUserId: input.ownerUserId }; const order: Order = input.publicOnly ? [['isPinned', 'DESC'], ['publishedAt', 'DESC'], ['id', 'ASC']] : [['updatedAt', 'DESC'], ['id', 'ASC']]; return (await model.findAll({ where, order, transaction: sequelizeTransaction(options.transaction) })).map((result) => row(result.get())); },
  async compareAndSwap(input, options) { const transaction = sequelizeTransaction(options.transaction); const [affected] = await model.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction }); return affected === 1 ? input.next : undefined; },
});
