import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsGuestCommentTableAttributes, TrailsGuestCommentTable } from '../../../../db/mysql/models/trailsGuestComment';
import { ITrailsGuestCommentAuditTableAttributes, TrailsGuestCommentAuditTable } from '../../../../db/mysql/models/trailsGuestCommentAudit';
import { ITrailsGuestCommentNotificationTableAttributes, TrailsGuestCommentNotificationTable } from '../../../../db/mysql/models/trailsGuestCommentNotification';
import { Actor, DurableGuestComment, DurableGuestCommentStore } from '../types';
import { actorCanManageCreatorSpace } from '../utils/actor';
import { TrailsSyncInputError } from './mysqlPortfolioCategorySync';

export class TrailsGuestCommentStaleVersionError extends Error {}
type ClaimedNotification = { tenantId: string; commentId: string; deliveryId: string; encryptedPayload: string; leaseToken: string; attempts: number };
export interface GuestCommentStorage { submit(input: DurableGuestComment & { email: string; verificationToken: string; notificationPayload: string }): Promise<DurableGuestComment>; verify(tokenHash: string, now: string): Promise<DurableGuestComment | undefined>; list(filter: Partial<DurableGuestComment>): Promise<DurableGuestComment[]>; transition(input: { id: string; tenantId: string; ownerUserId: string; status: DurableGuestComment['status']; resourceVersion: string; actorUserId?: string; now: string }): Promise<DurableGuestComment | undefined>; redact(input: { tenantId: string; ownerUserId: string; before: string; now: string }): Promise<number>; claim(commentId: string | undefined, limit: number, now: string): Promise<ClaimedNotification[]>; complete(claim: ClaimedNotification, outcome: 'sent' | 'retryable-failure' | 'failed', nextAttemptAt: string, now: string): Promise<boolean>; }
const hash = (value: string) => createHash('sha256').update(value).digest('hex');
export class MySqlGuestCommentRepository implements DurableGuestCommentStore {
  constructor(private readonly storage: GuestCommentStorage, private readonly encryptionKeyValue: string, private readonly now: () => Date = () => new Date()) { encryptionKey(encryptionKeyValue); }
  async submit(input: Parameters<DurableGuestCommentStore['submit']>[0]) { const timestamp = this.now().toISOString(); return this.storage.submit({ ...input, verificationTokenHash: hash(input.verificationToken), notificationPayload: encrypt(this.encryptionKeyValue, JSON.stringify({ email: input.email, token: input.verificationToken, expiresAt: input.verificationExpiresAt })), status: 'pending-verification', resourceVersion: '1', createdAt: timestamp, updatedAt: timestamp }); }
  async verify(input: { token: string }) { return this.storage.verify(hash(input.token), this.now().toISOString()); }
  async listModeration(actor: Actor) { return (await this.storage.list({ tenantId: actor.tenantId, status: 'pending-moderation' })).filter(item => actorCanManageCreatorSpace(actor, item)); }
  async moderate(actor: Actor, input: { id: string; status: 'approved' | 'rejected'; resourceVersion: string }) { const ownerUserId = actor.creatorSpaceRole === 'creator-space-editor' ? actor.creatorSpaceOwnerUserId : actor.userId; if (!ownerUserId) throw new TrailsSyncInputError('无权审核该留言'); const current = (await this.storage.list({ id: input.id, tenantId: actor.tenantId, ownerUserId }))[0]; if (!current) throw new TrailsSyncInputError('未找到留言'); if (!actorCanManageCreatorSpace(actor, current)) throw new TrailsSyncInputError('无权审核该留言'); if (current.status !== 'pending-moderation') throw new TrailsGuestCommentStaleVersionError(); const saved = await this.storage.transition({ id: input.id, tenantId: actor.tenantId, ownerUserId, status: input.status, resourceVersion: input.resourceVersion, actorUserId: actor.userId, now: this.now().toISOString() }); if (!saved) throw new TrailsGuestCommentStaleVersionError(); return saved; }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>, input: { subjectType: DurableGuestComment['subjectType']; subjectId?: string }) { return this.storage.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, ...input, status: 'approved' }); }
  async redactRetained(actor: Actor, input: { before: string }) { const ownerUserId = actor.creatorSpaceRole === 'creator-space-editor' ? actor.creatorSpaceOwnerUserId : actor.userId; if (!ownerUserId || !actorCanManageCreatorSpace(actor, { tenantId: actor.tenantId, ownerUserId })) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return this.storage.redact({ tenantId: actor.tenantId, ownerUserId, before: input.before, now: this.now().toISOString() }); }
  async dispatchPending(dispatcher: import('../types').CommentVerificationNotificationDispatcher, input: { commentId: string }) { const result = await this.dispatch(dispatcher, await this.storage.claim(input.commentId, 1, this.now().toISOString())); return result.sent ? { outcome: 'sent' as const } : result.retryableFailures ? { outcome: 'retryable-failure' as const } : result.failed ? { outcome: 'failed' as const } : { outcome: 'nothing-due' as const }; }
  async retryNotifications(actor: Actor, dispatcher: import('../types').CommentVerificationNotificationDispatcher, input: { limit: number }) { if (!actor.isAdmin || !Number.isInteger(input.limit) || input.limit < 1 || input.limit > 100) throw new TrailsSyncInputError('通知重试参数无效'); return this.dispatch(dispatcher, await this.storage.claim(undefined, input.limit, this.now().toISOString())); }
  private async dispatch(dispatcher: import('../types').CommentVerificationNotificationDispatcher, claims: ClaimedNotification[]) { let sent = 0; let retryableFailures = 0; let failed = 0; for (const claim of claims) { const timestamp = this.now().toISOString(); try { const payload = decrypt(this.encryptionKeyValue, claim.encryptedPayload); await dispatcher.dispatchVerification({ deliveryId: claim.deliveryId, email: payload.email, commentId: claim.commentId, verificationToken: payload.token, expiresAt: payload.expiresAt }); if (await this.storage.complete(claim, 'sent', timestamp, timestamp)) sent += 1; } catch { const terminal = claim.attempts >= 5; const retryAt = terminal ? timestamp : new Date(new Date(timestamp).getTime() + Math.min(3600000, 60000 * 2 ** Math.min(claim.attempts, 6))).toISOString(); if (await this.storage.complete(claim, terminal ? 'failed' : 'retryable-failure', retryAt, timestamp)) { if (terminal) failed += 1; else retryableFailures += 1; } } } return { attempted: claims.length, sent, retryableFailures, failed }; }
}

const encryptionKey = (value: string): Buffer => { const key = Buffer.from(value, 'base64'); if (key.length !== 32) throw new TrailsSyncInputError('留言通知加密密钥未配置'); return key; };
const encrypt = (keyValue: string, payload: string): string => { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', encryptionKey(keyValue), iv); const body = Buffer.concat([cipher.update(payload, 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${body.toString('base64url')}`; };
const decrypt = (keyValue: string, payload: string): { email: string; token: string; expiresAt: string } => { const [ivText, tagText, bodyText] = payload.split('.'); if (!ivText || !tagText || !bodyText) throw new Error('invalid notification payload'); const decipher = createDecipheriv('aes-256-gcm', encryptionKey(keyValue), Buffer.from(ivText, 'base64url')); decipher.setAuthTag(Buffer.from(tagText, 'base64url')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(bodyText, 'base64url')), decipher.final()]).toString('utf8')) as { email: string; token: string; expiresAt: string }; };

type Row = Omit<ITrailsGuestCommentTableAttributes, 'createdAt' | 'updatedAt' | 'verificationExpiresAt' | 'verifiedAt' | 'moderatedAt' | 'redactedAt'> & { createdAt: Date; updatedAt: Date; verificationExpiresAt?: Date; verifiedAt?: Date; moderatedAt?: Date; redactedAt?: Date };
type AuditRow = Omit<ITrailsGuestCommentAuditTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
const decimal = (value: unknown): string => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : (() => { throw new Error('invalid durable comment version'); })();
const record = (row: Row): DurableGuestComment => ({ id: row.id, tenantId: row.tenantId, ownerUserId: row.ownerUserId, subjectType: row.subjectType, ...(row.subjectId ? { subjectId: row.subjectId } : {}), displayName: row.displayName, avatarId: row.avatarId as DurableGuestComment['avatarId'], body: row.body, ...(row.verificationTokenHash ? { verificationTokenHash: row.verificationTokenHash } : {}), ...(row.verificationExpiresAt ? { verificationExpiresAt: row.verificationExpiresAt.toISOString() } : {}), status: row.status, resourceVersion: decimal(row.resourceVersion), ...(row.verifiedAt ? { verifiedAt: row.verifiedAt.toISOString() } : {}), ...(row.moderatedAt ? { moderatedAt: row.moderatedAt.toISOString() } : {}), ...(row.moderatedByUserId ? { moderatedByUserId: row.moderatedByUserId } : {}), ...(row.redactedAt ? { redactedAt: row.redactedAt.toISOString() } : {}), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() });
const audit = (comment: DurableGuestComment, operation: AuditRow['operation'], fromStatus: AuditRow['fromStatus'], actorUserId?: string): AuditRow => ({ eventId: `guest-comment-audit_${comment.id}_${comment.resourceVersion}_${operation}`, tenantId: comment.tenantId, commentId: comment.id, ...(actorUserId ? { actorUserId } : {}), operation, ...(fromStatus ? { fromStatus } : {}), toStatus: comment.status, resourceVersion: comment.resourceVersion, occurredAt: new Date(comment.updatedAt), createdAt: new Date(comment.updatedAt), updatedAt: new Date(comment.updatedAt) });
export const createSequelizeGuestCommentStorage = (comments: ModelStatic<TrailsGuestCommentTable>, audits: ModelStatic<TrailsGuestCommentAuditTable>, notifications: ModelStatic<TrailsGuestCommentNotificationTable>, key: string): GuestCommentStorage => {
  const transaction = async <T>(work: (tx: Transaction) => Promise<T>) => comments.sequelize!.transaction(work);
  const find = async (where: object, tx: Transaction) => { const found = await comments.findOne({ where: where as Partial<ITrailsGuestCommentTableAttributes>, transaction: tx, lock: tx.LOCK.UPDATE }); return found ? found.get() as Row : undefined; };
  return {
    async submit(input) { return transaction(async tx => { const timestamp = new Date(input.createdAt); const row: Row = { tenantId: input.tenantId, id: input.id, ownerUserId: input.ownerUserId, subjectType: input.subjectType, ...(input.subjectId ? { subjectId: input.subjectId } : {}), displayName: input.displayName, avatarId: input.avatarId, body: input.body, verificationTokenHash: input.verificationTokenHash, verificationExpiresAt: new Date(input.verificationExpiresAt!), status: input.status, resourceVersion: input.resourceVersion, createdAt: timestamp, updatedAt: timestamp }; const saved = record((await comments.create(row, { transaction: tx })).get() as Row); await audits.create(audit(saved, 'submitted', undefined), { transaction: tx }); await notifications.create({ tenantId: input.tenantId, commentId: input.id, deliveryId: `guest-comment-delivery_${input.tenantId}_${input.id}`, encryptedPayload: input.notificationPayload, status: 'pending', attempts: 0, nextAttemptAt: timestamp, createdAt: timestamp, updatedAt: timestamp }, { transaction: tx }); return saved; }); },
    async verify(tokenHash, now) { return transaction(async tx => { const current = await find({ verificationTokenHash: tokenHash, status: 'pending-verification' }, tx); if (!current || !current.verificationExpiresAt || current.verificationExpiresAt.getTime() <= new Date(now).getTime()) return undefined; const next: Row = { ...current, emailCiphertext: undefined, verificationTokenHash: undefined, verificationExpiresAt: undefined, status: 'pending-moderation', resourceVersion: String(BigInt(decimal(current.resourceVersion)) + BigInt(1)), verifiedAt: new Date(now), updatedAt: new Date(now) }; const [affected] = await comments.update(next, { where: { tenantId: current.tenantId, id: current.id, resourceVersion: current.resourceVersion }, transaction: tx }); if (affected !== 1) return undefined; const saved = record(next); await audits.create(audit(saved, 'verified', current.status), { transaction: tx }); return saved; }); },
    async list(filter) { return transaction(async tx => (await comments.findAll({ where: filter, transaction: tx, order: [['createdAt', 'ASC'], ['id', 'ASC']] })).map(item => record(item.get() as Row))); },
    async transition(input) { return transaction(async tx => { const current = await find({ tenantId: input.tenantId, ownerUserId: input.ownerUserId, id: input.id }, tx); if (!current || decimal(current.resourceVersion) !== input.resourceVersion) return undefined; const timestamp = new Date(input.now); const next: Row = { ...current, status: input.status, resourceVersion: String(BigInt(decimal(current.resourceVersion)) + BigInt(1)), moderatedAt: timestamp, ...(input.actorUserId ? { moderatedByUserId: input.actorUserId } : {}), updatedAt: timestamp }; const [affected] = await comments.update(next, { where: { tenantId: current.tenantId, ownerUserId: current.ownerUserId, id: current.id, resourceVersion: current.resourceVersion }, transaction: tx }); if (affected !== 1) return undefined; const saved = record(next); await audits.create(audit(saved, 'moderated', current.status, input.actorUserId), { transaction: tx }); return saved; }); },
    async redact(input) { return transaction(async tx => { const rows = await comments.findAll({ where: { tenantId: input.tenantId, ownerUserId: input.ownerUserId }, transaction: tx, lock: tx.LOCK.UPDATE }); let count = 0; for (const item of rows) { const current = item.get() as Row; if (current.createdAt.getTime() >= new Date(input.before).getTime() || current.status === 'redacted') continue; const next: Row = { ...current, displayName: 'Deleted guest', body: '[redacted]', emailHash: undefined, emailCiphertext: undefined, verificationTokenHash: undefined, verificationExpiresAt: undefined, status: 'redacted', resourceVersion: String(BigInt(decimal(current.resourceVersion)) + BigInt(1)), redactedAt: new Date(input.now), updatedAt: new Date(input.now) }; const [affected] = await comments.update(next, { where: { tenantId: current.tenantId, id: current.id, resourceVersion: current.resourceVersion }, transaction: tx }); if (affected === 1) { await notifications.destroy({ where: { tenantId: current.tenantId, commentId: current.id }, transaction: tx }); const saved = record(next); await audits.create(audit(saved, 'redacted', current.status), { transaction: tx }); count += 1; } } return count; }); },
    async claim(commentId, limit, now) { return transaction(async tx => { const due = await notifications.findAll({ where: commentId ? { commentId, status: ['pending', 'retryable-failure', 'processing'] } : { status: ['pending', 'retryable-failure', 'processing'] }, transaction: tx, lock: tx.LOCK.UPDATE, limit }); const claimed: ClaimedNotification[] = []; for (const item of due) { const current = item.get() as ITrailsGuestCommentNotificationTableAttributes; const reclaimable = current.status === 'processing' && current.leaseExpiresAt && current.leaseExpiresAt.getTime() <= new Date(now).getTime(); if ((current.status === 'processing' && !reclaimable) || (current.status !== 'processing' && current.nextAttemptAt.getTime() > new Date(now).getTime())) continue; const leaseToken = randomBytes(20).toString('base64url'); const expiresAt = new Date(new Date(now).getTime() + 300000); const [affected] = await notifications.update({ status: 'processing', attempts: current.attempts + 1, leaseToken, leaseExpiresAt: expiresAt, lastAttemptAt: new Date(now), updatedAt: new Date(now) }, { where: { tenantId: current.tenantId, commentId: current.commentId, status: current.status, ...(current.status === 'processing' ? { leaseToken: current.leaseToken, leaseExpiresAt: current.leaseExpiresAt } : { nextAttemptAt: current.nextAttemptAt }) }, transaction: tx }); if (affected === 1) claimed.push({ tenantId: current.tenantId, commentId: current.commentId, deliveryId: current.deliveryId, encryptedPayload: current.encryptedPayload, leaseToken, attempts: current.attempts + 1 }); } return claimed; }); },
    async complete(claim, outcome, nextAttemptAt, now) { return transaction(async tx => { const values: Partial<ITrailsGuestCommentNotificationTableAttributes> = outcome === 'sent' ? { status: 'sent', sentAt: new Date(now), nextAttemptAt: new Date(nextAttemptAt), leaseToken: undefined, leaseExpiresAt: undefined, updatedAt: new Date(now) } : { status: outcome, nextAttemptAt: new Date(nextAttemptAt), leaseToken: undefined, leaseExpiresAt: undefined, updatedAt: new Date(now) }; const [affected] = await notifications.update(values, { where: { tenantId: claim.tenantId, commentId: claim.commentId, status: 'processing', leaseToken: claim.leaseToken }, transaction: tx }); return affected === 1; }); },
  };
};
