import { createHash } from 'crypto';
import { ModelStatic, Transaction } from 'sequelize';
import { ITrailsDurableGuidedTripTableAttributes, TrailsDurableGuidedTripTable } from '../../../../db/mysql/models/trailsDurableGuidedTrip';
import { ITrailsDurableGuidedTripMutationTableAttributes, TrailsDurableGuidedTripMutationTable } from '../../../../db/mysql/models/trailsDurableGuidedTripMutation';
import { ITrailsDurableGuidedTripAuditTableAttributes, TrailsDurableGuidedTripAuditTable } from '../../../../db/mysql/models/trailsDurableGuidedTripAudit';
import { Actor, DurableGuidedTrip, DurableGuidedTripDraftInput, DurableGuidedTripMutation, DurableGuidedTripStatus, DurableGuidedTripStore } from '../types';
import { creatorSpaceOwnerId } from '../utils/actor';
import { TrailsSyncInputError, TrailsSyncPersistenceError, TrailsSyncTransaction } from './mysqlPortfolioCategorySync';

type Row = Omit<ITrailsDurableGuidedTripTableAttributes, 'createdAt' | 'updatedAt'> & { createdAt: Date; updatedAt: Date };
type Options = { transaction: TrailsSyncTransaction };
export class TrailsDurableGuidedTripStaleVersionError extends Error { constructor(public readonly current: DurableGuidedTrip) { super('行摄计划版本已过期'); } }
const safeText = (value: unknown, label: string, max: number) => { if (typeof value !== 'string') throw new TrailsSyncInputError(`${label}无效`); const result = value.trim(); if (!result || result.length > max || /[<>]|[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(result)) throw new TrailsSyncInputError(`${label}无效`); return result; };
const opaque = (value: unknown, label: string) => { const result = safeText(value, label, 160); if (!/^[A-Za-z0-9_-]+$/.test(result)) throw new TrailsSyncInputError(`${label}必须是安全不透明标识`); return result; };
const decimal = (value: unknown, label: string) => { if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) throw new TrailsSyncInputError(`${label}必须是规范十进制字符串`); return value; };
const version = (value: unknown) => typeof value === 'string' && /^(0|[1-9][0-9]*)$/.test(value) ? value : typeof value === 'number' && Number.isSafeInteger(value) ? String(value) : typeof value === 'bigint' ? value.toString() : (() => { throw new TrailsSyncPersistenceError('行摄计划版本无效'); })();
const date = (value: unknown, label: string) => { const result = safeText(value, label, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(result) || new Date(`${result}T00:00:00.000Z`).toISOString().slice(0, 10) !== result) throw new TrailsSyncInputError(`${label}必须是ISO日期`); return result; };
const payload = (value: Record<string, unknown>): Omit<DurableGuidedTripDraftInput, 'id'> => { const startsOn = date(value.startsOn, 'startsOn'); const endsOn = date(value.endsOn, 'endsOn'); if (endsOn < startsOn) throw new TrailsSyncInputError('endsOn不能早于startsOn'); const locationLabel = safeText(value.locationLabel, 'locationLabel', 240); if (/[-+]?\d{1,2}\.\d{3,}\s*[,，]\s*[-+]?\d{1,3}\.\d{3,}|\b(meet(?:ing)?|meeting point|route access|parking)\b|集合点|会合点|停车|路线入口/i.test(locationLabel)) throw new TrailsSyncInputError('locationLabel必须是一般地点描述'); const itinerary = value.itinerary; const checklist = value.checklist; const materialReferences = value.materialReferences; if (!Array.isArray(itinerary) || itinerary.length > 31 || !Array.isArray(checklist) || checklist.length > 50 || !Array.isArray(materialReferences) || materialReferences.length > 50) throw new TrailsSyncInputError('行程数组无效'); const parsedItinerary = itinerary.map((x, i) => { if (!x || typeof x !== 'object' || Array.isArray(x)) throw new TrailsSyncInputError(`itinerary[${i}]无效`); const v = x as Record<string, unknown>; return { dayLabel: safeText(v.dayLabel, `itinerary[${i}].dayLabel`, 80), summary: safeText(v.summary, `itinerary[${i}].summary`, 2000) }; }); const parsedChecklist = checklist.map((x, i) => safeText(x, `checklist[${i}]`, 300)); if (new Set(parsedChecklist).size !== parsedChecklist.length) throw new TrailsSyncInputError('checklist不能重复'); const parsedMaterials = materialReferences.map((x, i) => { if (!x || typeof x !== 'object' || Array.isArray(x)) throw new TrailsSyncInputError(`materialReferences[${i}]无效`); const v = x as Record<string, unknown>; return { label: safeText(v.label, `materialReferences[${i}].label`, 160), reference: opaque(v.reference, `materialReferences[${i}].reference`) }; }); if (new Set(parsedMaterials.map(x => x.reference)).size !== parsedMaterials.length) throw new TrailsSyncInputError('materialReferences不能重复'); return { title: safeText(value.title, 'title', 160), summary: safeText(value.summary, 'summary', 4000), locationLabel, startsOn, endsOn, itinerary: parsedItinerary, checklist: parsedChecklist, materialReferences: parsedMaterials, ...(value.publicContingencyMessage === undefined ? {} : { publicContingencyMessage: safeText(value.publicContingencyMessage, 'publicContingencyMessage', 2000) }) }; };
const readPayload = (row: Row) => { try { const value = JSON.parse(row.payloadJson) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return payload(value as Record<string, unknown>); } catch (error) { if (error instanceof TrailsSyncInputError) throw error; throw new TrailsSyncPersistenceError('行摄计划载荷无效'); } };
const fromRow = (row: Row): DurableGuidedTrip => ({ id: row.id, tenantId: row.tenantId, ownerUserId: row.ownerUserId, ...readPayload(row), status: row.status as DurableGuidedTripStatus, resourceVersion: version(row.resourceVersion), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), ...(row.publishedAt ? { publishedAt: row.publishedAt.toISOString() } : {}), ...(row.cancelledAt ? { cancelledAt: row.cancelledAt.toISOString() } : {}) });
export interface GuidedTripModel { create(row: Row, options: Options): Promise<Row>; find(input: { tenantId: string; id: string }, options: Options): Promise<Row | undefined>; list(input: { tenantId: string; ownerUserId: string; status?: string }, options: Options): Promise<Row[]>; cas(input: { tenantId: string; id: string; expectedVersion: string; next: Row }, options: Options): Promise<Row | undefined>; }
export interface GuidedTripMutationModel { find(input: { tenantId: string; actorUserId: string; mutationId: string }, options: Options): Promise<ITrailsDurableGuidedTripMutationTableAttributes | undefined>; create(row: ITrailsDurableGuidedTripMutationTableAttributes, options: Options): Promise<void>; }
export interface GuidedTripAuditModel { create(row: ITrailsDurableGuidedTripAuditTableAttributes, options: Options): Promise<void>; }
export class MySqlDurableGuidedTripRepository implements DurableGuidedTripStore {
  constructor(private readonly connection: { transaction<T>(work: (transaction: TrailsSyncTransaction) => Promise<T>): Promise<T> }, private readonly trips: GuidedTripModel, private readonly mutations: GuidedTripMutationModel, private readonly audits: GuidedTripAuditModel, private readonly now: () => Date = () => new Date()) {}
  private owner(actor: Actor) { const owner = creatorSpaceOwnerId(actor); if (!owner) throw new TrailsSyncInputError('当前账号没有创作空间管理权限'); return owner; }
  private async mutation<T>(actor: Actor, input: DurableGuidedTripMutation, operation: string, work: (tx: TrailsSyncTransaction) => Promise<T>) { const mutationId = opaque(input.mutationId, 'mutationId'); if (input.expectedResourceVersion !== null) decimal(input.expectedResourceVersion, 'expectedResourceVersion'); const fingerprint = createHash('sha256').update(JSON.stringify({ operation, input })).digest('hex'); return this.connection.transaction(async transaction => { const prior = await this.mutations.find({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId }, { transaction }); if (prior) { if (prior.fingerprint !== fingerprint) throw new TrailsSyncInputError('mutationId不能用于不同的写入'); return JSON.parse(prior.resultJson) as T; } const result = await work(transaction); await this.mutations.create({ tenantId: actor.tenantId, actorUserId: actor.userId, mutationId, fingerprint, resultJson: JSON.stringify(result) }, { transaction }); return result; }); }
  private async row(actor: Actor, id: string, tx: TrailsSyncTransaction) { const row = await this.trips.find({ tenantId: actor.tenantId, id: opaque(id, 'id') }, { transaction: tx }); if (!row || row.ownerUserId !== this.owner(actor)) throw new TrailsSyncInputError('行摄计划不存在或不属于当前创作空间'); return row; }
  private async audit(actor: Actor, row: Row, mutationId: string, operation: string, fromVersion: string | undefined, tx: TrailsSyncTransaction) { await this.audits.create({ eventId: `guided-trip-audit_${createHash('sha256').update(`${actor.tenantId}:${actor.userId}:${mutationId}`).digest('hex')}`, tenantId: row.tenantId, tripId: row.id, actorUserId: actor.userId, ownerUserId: row.ownerUserId, mutationId, operation, ...(fromVersion ? { fromVersion } : {}), toVersion: version(row.resourceVersion), occurredAt: row.updatedAt }, { transaction: tx }); }
  async createDraft(actor: Actor, input: DurableGuidedTripMutation & DurableGuidedTripDraftInput) { return this.mutation(actor, input, 'create-draft', async tx => { if (input.expectedResourceVersion !== null) throw new TrailsSyncInputError('新行摄计划必须使用null版本'); const time = this.now(); const values = payload(input as unknown as Record<string, unknown>); const row: Row = { tenantId: actor.tenantId, id: opaque(input.id, 'id'), ownerUserId: this.owner(actor), status: 'draft', startsOn: values.startsOn, resourceVersion: '1', payloadJson: JSON.stringify(values), createdAt: time, updatedAt: time }; const saved = await this.trips.create(row, { transaction: tx }); await this.audit(actor, saved, input.mutationId, 'create-draft', undefined, tx); return fromRow(saved); }); }
  async updateDraft(actor: Actor, input: DurableGuidedTripMutation & DurableGuidedTripDraftInput) { return this.change(actor, input, 'update-draft', 'draft', row => { const values = payload(input as unknown as Record<string, unknown>); return { ...row, startsOn: values.startsOn, payloadJson: JSON.stringify(values) }; }); }
  async publish(actor: Actor, input: DurableGuidedTripMutation & { id: string }) { return this.change(actor, input, 'publish', 'draft', row => ({ ...row, status: 'published', publishedAt: this.now() })); }
  async unpublish(actor: Actor, input: DurableGuidedTripMutation & { id: string }) { return this.change(actor, input, 'unpublish', 'published', row => ({ ...row, status: 'draft', publishedAt: undefined })); }
  async cancel(actor: Actor, input: DurableGuidedTripMutation & { id: string }) { return this.change(actor, input, 'cancel', undefined, row => ({ ...row, status: 'cancelled', cancelledAt: this.now() })); }
  private async change(actor: Actor, input: DurableGuidedTripMutation & { id: string }, operation: 'update-draft' | 'publish' | 'unpublish' | 'cancel', required: DurableGuidedTripStatus | undefined, patch: (row: Row) => Partial<Row>) { return this.mutation(actor, input, operation, async tx => { const row = await this.row(actor, input.id, tx); if (input.expectedResourceVersion !== row.resourceVersion) throw new TrailsDurableGuidedTripStaleVersionError(fromRow(row)); if (row.status === 'cancelled' || (required && row.status !== required)) throw new TrailsSyncInputError('当前行摄计划不允许该操作'); const time = this.now(); const next: Row = { ...row, ...patch(row), resourceVersion: (BigInt(row.resourceVersion) + BigInt(1)).toString(), updatedAt: time }; const saved = await this.trips.cas({ tenantId: row.tenantId, id: row.id, expectedVersion: row.resourceVersion, next }, { transaction: tx }); if (!saved) { const current = await this.row(actor, input.id, tx); throw new TrailsDurableGuidedTripStaleVersionError(fromRow(current)); } await this.audit(actor, saved, input.mutationId, operation, row.resourceVersion, tx); return fromRow(saved); }); }
  async listWorkspace(actor: Actor) { return this.connection.transaction(async tx => (await this.trips.list({ tenantId: actor.tenantId, ownerUserId: this.owner(actor) }, { transaction: tx })).map(fromRow)); }
  async listPublic(owner: Pick<Actor, 'tenantId' | 'userId'>) { return this.connection.transaction(async tx => (await this.trips.list({ tenantId: owner.tenantId, ownerUserId: owner.userId, status: 'published' }, { transaction: tx })).map(fromRow)); }
  async readPublic(owner: Pick<Actor, 'tenantId' | 'userId'>, id: string) { return this.connection.transaction(async tx => { const row = await this.trips.find({ tenantId: owner.tenantId, id: opaque(id, 'id') }, { transaction: tx }); return row && row.ownerUserId === owner.userId && row.status === 'published' ? fromRow(row) : undefined; }); }
}
const row = (value: ITrailsDurableGuidedTripTableAttributes): Row => { if (!value.createdAt || !value.updatedAt) throw new TrailsSyncPersistenceError('行摄计划行无效'); return { ...value, resourceVersion: version(value.resourceVersion), createdAt: value.createdAt, updatedAt: value.updatedAt }; };
const tx = (value: TrailsSyncTransaction) => { if (!(value instanceof Transaction)) throw new TrailsSyncPersistenceError('Sequelize adapter requires a managed transaction'); return value; };
export const createSequelizeDurableGuidedTripModels = (trips: ModelStatic<TrailsDurableGuidedTripTable>, mutations: ModelStatic<TrailsDurableGuidedTripMutationTable>, audits: ModelStatic<TrailsDurableGuidedTripAuditTable>): { trips: GuidedTripModel; mutations: GuidedTripMutationModel; audits: GuidedTripAuditModel } => ({ trips: { async create(input, options) { return row((await trips.create(input, { transaction: tx(options.transaction) })).get()); }, async find(input, options) { const transaction = tx(options.transaction); const value = await trips.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return value ? row(value.get()) : undefined; }, async list(input, options) { return (await trips.findAll({ where: input, order: [['startsOn', 'ASC'], ['id', 'ASC']], transaction: tx(options.transaction) })).map(value => row(value.get())); }, async cas(input, options) { const [changed] = await trips.update(input.next, { where: { tenantId: input.tenantId, id: input.id, resourceVersion: input.expectedVersion }, transaction: tx(options.transaction) }); return changed === 1 ? input.next : undefined; } }, mutations: { async find(input, options) { const transaction = tx(options.transaction); const value = await mutations.findOne({ where: input, transaction, lock: transaction.LOCK.UPDATE }); return value?.get(); }, async create(input, options) { await mutations.create(input, { transaction: tx(options.transaction) }); } }, audits: { async create(input, options) { await audits.create(input, { transaction: tx(options.transaction) }); } } });
