import { DataTypes, Model, Sequelize } from 'sequelize';
import { DataBaseTableNames } from 'typings';

export interface ITrailsTrustedPhotoshopStorageWriteFenceTableAttributes {
  tenantId: string; operationId: string; slot: string; intentDigest: string; objectIdentity: string; mimeType: string; byteLength: string; sha256: string; state: string; fenceToken?: string; issuedAt?: Date; recordedAt?: Date; createdAt?: Date; updatedAt?: Date;
}
export class TrailsTrustedPhotoshopStorageWriteFenceTable extends Model<ITrailsTrustedPhotoshopStorageWriteFenceTableAttributes> implements ITrailsTrustedPhotoshopStorageWriteFenceTableAttributes {
  public tenantId!: string; public operationId!: string; public slot!: string; public intentDigest!: string; public objectIdentity!: string; public mimeType!: string; public byteLength!: string; public sha256!: string; public state!: string; public fenceToken?: string; public issuedAt?: Date; public recordedAt?: Date; public readonly createdAt!: Date; public readonly updatedAt!: Date;
}
export default function (sequelize: Sequelize) { return TrailsTrustedPhotoshopStorageWriteFenceTable.init({
  tenantId: { type: DataTypes.STRING(64), field: 'tenant_id', primaryKey: true }, operationId: { type: DataTypes.STRING(160), field: 'operation_id', primaryKey: true }, slot: { type: DataTypes.ENUM('master', 'grid-960:avif', 'grid-960:webp', 'grid-960:jpeg', 'cover-2048:avif', 'cover-2048:webp', 'cover-2048:jpeg', 'preview-4096:avif', 'preview-4096:webp', 'preview-4096:jpeg'), primaryKey: true }, intentDigest: { type: DataTypes.CHAR(64), field: 'intent_digest', allowNull: false }, objectIdentity: { type: DataTypes.CHAR(64), field: 'object_identity', allowNull: false }, mimeType: { type: DataTypes.STRING(160), field: 'mime_type', allowNull: false }, byteLength: { type: DataTypes.BIGINT.UNSIGNED, field: 'byte_length', allowNull: false }, sha256: { type: DataTypes.CHAR(64), allowNull: false }, state: { type: DataTypes.ENUM('pending', 'issued', 'recorded'), allowNull: false }, fenceToken: { type: DataTypes.CHAR(64), field: 'fence_token' }, issuedAt: { type: DataTypes.DATE, field: 'issued_at' }, recordedAt: { type: DataTypes.DATE, field: 'recorded_at' }, createdAt: { type: DataTypes.DATE, field: 'created_at', defaultValue: DataTypes.NOW }, updatedAt: { type: DataTypes.DATE, field: 'updated_at', defaultValue: DataTypes.NOW },
}, { sequelize, tableName: DataBaseTableNames.TrailsTrustedPhotoshopStorageWriteFence, modelName: DataBaseTableNames.TrailsTrustedPhotoshopStorageWriteFence, timestamps: true }); }
