import { DataTypes, Model, Sequelize } from 'sequelize';
import { DataBaseTableNames } from 'typings';

export interface ITrailsTrustedPhotoshopIngestionOperationTableAttributes {
  tenantId: string; operationId: string; ownerUserId: string; assetId: string; assetFingerprint: string; intentDigest: string; registerMutationId: string; artifactMutationId: string; phase: string; resourceVersion: string;
  preparedAt?: Date; storagePendingAt?: Date; storageRecordedAt?: Date; registryMasterPendingAt?: Date; registryMasterRecordedAt?: Date; registryArtifactsPendingAt?: Date; completedAt?: Date; blockedAmbiguousAt?: Date; cleanupPendingAt?: Date; cleanedAt?: Date; failedAt?: Date;
  leaseOwner?: string; leaseExpiresAt?: Date; failureClass?: string; masterLocator?: string; masterMimeType: string; masterByteLength: string; masterSha256: string; registryMasterVersion?: string; registryArtifactsVersion?: string; createdAt?: Date; updatedAt?: Date;
}
export class TrailsTrustedPhotoshopIngestionOperationTable extends Model<ITrailsTrustedPhotoshopIngestionOperationTableAttributes> implements ITrailsTrustedPhotoshopIngestionOperationTableAttributes {
  public tenantId!: string; public operationId!: string; public ownerUserId!: string; public assetId!: string; public assetFingerprint!: string; public intentDigest!: string; public registerMutationId!: string; public artifactMutationId!: string; public phase!: string; public resourceVersion!: string;
  public preparedAt?: Date; public storagePendingAt?: Date; public storageRecordedAt?: Date; public registryMasterPendingAt?: Date; public registryMasterRecordedAt?: Date; public registryArtifactsPendingAt?: Date; public completedAt?: Date; public blockedAmbiguousAt?: Date; public cleanupPendingAt?: Date; public cleanedAt?: Date; public failedAt?: Date;
  public leaseOwner?: string; public leaseExpiresAt?: Date; public failureClass?: string; public masterLocator?: string; public masterMimeType!: string; public masterByteLength!: string; public masterSha256!: string; public registryMasterVersion?: string; public registryArtifactsVersion?: string; public readonly createdAt!: Date; public readonly updatedAt!: Date;
}
export default function (sequelize: Sequelize) { return TrailsTrustedPhotoshopIngestionOperationTable.init({
  tenantId: { type: DataTypes.STRING(64), field: 'tenant_id', primaryKey: true }, operationId: { type: DataTypes.STRING(160), field: 'operation_id', primaryKey: true }, ownerUserId: { type: DataTypes.STRING(64), field: 'owner_user_id', allowNull: false }, assetId: { type: DataTypes.STRING(160), field: 'asset_id', allowNull: false }, assetFingerprint: { type: DataTypes.CHAR(64), field: 'asset_fingerprint', allowNull: false }, intentDigest: { type: DataTypes.CHAR(64), field: 'intent_digest', allowNull: false }, registerMutationId: { type: DataTypes.STRING(160), field: 'register_mutation_id', allowNull: false }, artifactMutationId: { type: DataTypes.STRING(160), field: 'artifact_mutation_id', allowNull: false }, phase: { type: DataTypes.ENUM('prepared', 'storage_pending', 'storage_recorded', 'registry_master_pending', 'registry_master_recorded', 'registry_artifacts_pending', 'completed', 'blocked_ambiguous', 'cleanup_pending', 'cleaned', 'failed'), allowNull: false }, resourceVersion: { type: DataTypes.BIGINT.UNSIGNED, field: 'resource_version', allowNull: false },
  preparedAt: { type: DataTypes.DATE, field: 'prepared_at' }, storagePendingAt: { type: DataTypes.DATE, field: 'storage_pending_at' }, storageRecordedAt: { type: DataTypes.DATE, field: 'storage_recorded_at' }, registryMasterPendingAt: { type: DataTypes.DATE, field: 'registry_master_pending_at' }, registryMasterRecordedAt: { type: DataTypes.DATE, field: 'registry_master_recorded_at' }, registryArtifactsPendingAt: { type: DataTypes.DATE, field: 'registry_artifacts_pending_at' }, completedAt: { type: DataTypes.DATE, field: 'completed_at' }, blockedAmbiguousAt: { type: DataTypes.DATE, field: 'blocked_ambiguous_at' }, cleanupPendingAt: { type: DataTypes.DATE, field: 'cleanup_pending_at' }, cleanedAt: { type: DataTypes.DATE, field: 'cleaned_at' }, failedAt: { type: DataTypes.DATE, field: 'failed_at' },
  leaseOwner: { type: DataTypes.STRING(160), field: 'lease_owner' }, leaseExpiresAt: { type: DataTypes.DATE, field: 'lease_expires_at' }, failureClass: { type: DataTypes.ENUM('validation', 'storage', 'registry', 'cleanup', 'internal'), field: 'failure_class' }, masterLocator: { type: DataTypes.STRING(512), field: 'master_locator' }, masterMimeType: { type: DataTypes.STRING(160), field: 'master_mime_type', allowNull: false }, masterByteLength: { type: DataTypes.BIGINT.UNSIGNED, field: 'master_byte_length', allowNull: false }, masterSha256: { type: DataTypes.CHAR(64), field: 'master_sha256', allowNull: false }, registryMasterVersion: { type: DataTypes.BIGINT.UNSIGNED, field: 'registry_master_version' }, registryArtifactsVersion: { type: DataTypes.BIGINT.UNSIGNED, field: 'registry_artifacts_version' }, createdAt: { type: DataTypes.DATE, field: 'created_at', defaultValue: DataTypes.NOW }, updatedAt: { type: DataTypes.DATE, field: 'updated_at', defaultValue: DataTypes.NOW },
}, { sequelize, tableName: DataBaseTableNames.TrailsTrustedPhotoshopIngestionOperation, modelName: DataBaseTableNames.TrailsTrustedPhotoshopIngestionOperation, timestamps: true }); }
