import { Starlight } from '../../src/typings';
import trailsActions from '../../src/apps/starlight/trails/actions';
import { InMemoryTrailsRepository } from '../../src/apps/starlight/trails/repository';
import { Actor, DurableMediaAssetRegistryStore, DurableMediaCommerceStore } from '../../src/apps/starlight/trails/types';
import { TrailsDurableMediaCommerceStaleVersionError } from '../../src/apps/starlight/trails/repository/mysqlDurableMediaCommerce';

const owner: Actor = { tenantId: 'tenant-a', userId: 'owner-a', isAdmin: false, creatorSpaceRole: 'creator-space-owner' };
const buyer: Actor = { tenantId: owner.tenantId, userId: 'buyer-a', isAdmin: false };
const star = { emit: jest.fn() } as unknown as Starlight;
const ctx = (actor: Actor | undefined, params: object) => ({ meta: actor ? { tenantId: actor.tenantId, user: actor } : {}, params });
const store = (overrides: Partial<DurableMediaCommerceStore> = {}): DurableMediaCommerceStore => ({
  createMedia: jest.fn(async () => ({ id: 'media-1', tenantId: owner.tenantId, ownerUserId: owner.userId, title: 'Night', summary: 'Sky', status: 'draft' as const, publicDerivativeReferences: [], resourceVersion: '1', createdAt: '', updatedAt: '' })), transitionMedia: jest.fn(), createEdition: jest.fn(async () => ({ id: 'edition-1', tenantId: owner.tenantId, ownerUserId: owner.userId, mediaId: 'media-1', title: 'Paper', description: 'Fine', currency: 'USD', priceMinor: 0, status: 'draft' as const, resourceVersion: '1', createdAt: '', updatedAt: '' })), transitionEdition: jest.fn(), inquireCommercial: jest.fn(), requestDownloadLicense: jest.fn(), decideDownloadLicense: jest.fn(), createOrder: jest.fn(), transitionOrder: jest.fn(), listPublic: jest.fn(async () => ({ media: [{ id: 'media-1', tenantId: owner.tenantId, ownerUserId: owner.userId, title: 'Night', summary: 'Sky', status: 'published' as const, publicDerivativeReferences: [{ reference: 'preview_1' }], resourceVersion: '2', createdAt: '', updatedAt: '' }], editions: [{ id: 'edition-1', tenantId: owner.tenantId, ownerUserId: owner.userId, mediaId: 'media-1', title: 'Paper', description: 'Fine', currency: 'USD', priceMinor: 1200, status: 'sellable' as const, resourceVersion: '2', createdAt: '', updatedAt: '' }] })), listBuyer: jest.fn(async () => ({ inquiries: [], requests: [], entitlements: [], orders: [] })), listOwner: jest.fn(async () => ({ media: [], editions: [], inquiries: [], requests: [], entitlements: [], orders: [] })), ...overrides,
});
const registry = (overrides: Partial<DurableMediaAssetRegistryStore> = {}): DurableMediaAssetRegistryStore => ({
  listWorkspacePicker: jest.fn(async () => [{ id: 'asset-1', lifecycle: 'published' as const, readiness: 'ready' as const, mimeType: 'image/jpeg', renditions: [{ name: 'grid-800' as const, width: 800, height: 600, reference: 'grid_ref' }]}]), register: jest.fn(), registerVariant: jest.fn(), persistArtifacts: jest.fn(), publish: jest.fn(), ...overrides,
});

describe('v2 durable media commerce actions', () => {
  it('fails closed without the v2 store and never reads v1', async () => { const response = await trailsActions(star, { repository: new InMemoryTrailsRepository() })['v2.commerce.buyer.workspace'].handler(ctx(buyer, {}) as never); expect(response.status).toBe(503); });
  it('derives owner identity and demands mutation/version inputs', async () => { const durable = store(); const actions = trailsActions(star, { repository: new InMemoryTrailsRepository(), durableMediaCommerceStore: durable }); const response = await actions['v2.commerce.media.create'].handler(ctx(owner, { mutationId: 'm1', expectedResourceVersion: null, title: 'Night', summary: 'Sky', derivativeReferences: [], tenantId: 'spoofed', ownerUserId: 'spoofed' }) as never); const invalid = await actions['v2.commerce.media.create'].handler(ctx(owner, { mutationId: 'm2', title: 'Night', summary: 'Sky', derivativeReferences: [] }) as never); expect(response.status).toBe(201); expect(durable.createMedia).toHaveBeenCalledWith(owner, expect.objectContaining({ expectedResourceVersion: null })); expect(invalid.status).toBe(400); });
  it('publicly projects only archive-safe media and edition fields', async () => { const durable = store(); const action = trailsActions(star, { repository: new InMemoryTrailsRepository(), durableMediaCommerceStore: durable, publicOwnerResolver: { resolve: () => ({ tenantId: owner.tenantId, ownerUserId: owner.userId }) } })['v2.commerce.public']; const response = await (action.handler as (context: unknown) => Promise<unknown>)(ctx(undefined, {})) as { status: number; data: { content: unknown } }; const content = response.data.content as { media: Array<Record<string, unknown>>; editions: Array<Record<string, unknown>> }; expect(response.status).toBe(200); expect(content.media[0]).toEqual({ id: 'media-1', title: 'Night', summary: 'Sky', derivatives: [{ reference: 'preview_1' }] }); expect(content.media[0]).not.toHaveProperty('ownerUserId'); expect(content.editions[0]).toEqual({ id: 'edition-1', mediaId: 'media-1', title: 'Paper', description: 'Fine' }); expect(content.editions[0]).not.toHaveProperty('currency'); expect(content.editions[0]).not.toHaveProperty('priceMinor'); expect(content.editions[0]).not.toHaveProperty('resourceVersion'); });
  it('maps stale versions to conflict and does not perform external work', async () => { const durable = store({ transitionOrder: jest.fn(async () => { throw new TrailsDurableMediaCommerceStaleVersionError('stale'); }) }); const response = await trailsActions(star, { repository: new InMemoryTrailsRepository(), durableMediaCommerceStore: durable })['v2.commerce.orders.transition'].handler(ctx(owner, { mutationId: 'm3', expectedResourceVersion: '1', id: 'order-1', status: 'fulfilled' }) as never); expect(response.status).toBe(409); });
  it('projects catalog-only owner data and resolves media derivatives from the trusted picker', async () => {
    const durable = store({ listOwner: jest.fn(async () => ({ media: [{ id: 'media-1', tenantId: owner.tenantId, ownerUserId: owner.userId, title: 'Night', summary: 'Sky', status: 'draft' as const, publicDerivativeReferences: [{ reference: 'grid_ref', width: 800, height: 600 }], resourceVersion: '1', createdAt: '', updatedAt: '' }], editions: [{ id: 'edition-1', tenantId: owner.tenantId, ownerUserId: owner.userId, mediaId: 'media-1', title: 'Paper', description: 'Fine', currency: 'USD', priceMinor: 0, status: 'draft' as const, resourceVersion: '1', createdAt: '', updatedAt: '' }], inquiries: [], requests: [], entitlements: [], orders: [] })) }); const assets = registry(); const actions = trailsActions(star, { repository: new InMemoryTrailsRepository(), durableMediaCommerceStore: durable, durableMediaAssetRegistryStore: assets });
    const workspace = await actions['v2.commerce.catalog.workspace'].handler(ctx(owner, {}) as never) as { status: number; data: { content: Record<string, unknown> } };
    const created = await actions['v2.commerce.catalog.media.create'].handler(ctx(owner, { assetId: 'asset-1', title: 'Night', summary: 'Sky', mutationId: 'catalog-create', expectedResourceVersion: null }) as never);
    const unsafe = await actions['v2.commerce.catalog.media.create'].handler(ctx(owner, { assetId: 'asset-1', title: 'Night', summary: 'Sky', mutationId: 'catalog-unsafe', expectedResourceVersion: null, derivativeReferences: [] }) as never);
    expect(workspace.status).toBe(200); expect(workspace.data.content).toEqual({ media: [{ id: 'media-1', title: 'Night', summary: 'Sky', status: 'draft', derivatives: [{ reference: 'grid_ref', width: 800, height: 600 }], resourceVersion: '1' }], editions: [{ id: 'edition-1', mediaId: 'media-1', title: 'Paper', description: 'Fine', status: 'draft', resourceVersion: '1' }] });
    expect(created.status).toBe(201); expect(durable.createMedia).toHaveBeenCalledWith(owner, expect.objectContaining({ derivativeReferences: [{ reference: 'grid_ref', width: 800, height: 600 }] })); expect(unsafe.status).toBe(400);
  });
  it('keeps price values server-owned and rejects catalog price injection before store creation', async () => {
    const durable = store(); const actions = trailsActions(star, { repository: new InMemoryTrailsRepository(), durableMediaCommerceStore: durable });
    const created = await actions['v2.commerce.catalog.editions.create'].handler(ctx(owner, { mediaId: 'media-1', title: 'Paper', description: 'Fine', mutationId: 'catalog-edition', expectedResourceVersion: null }) as never) as { status: number; data: { content: Record<string, unknown> } };
    const currencyInjected = await actions['v2.commerce.catalog.editions.create'].handler(ctx(owner, { mediaId: 'media-1', title: 'Paper', description: 'Fine', mutationId: 'catalog-edition-currency', expectedResourceVersion: null, currency: 'CNY' }) as never);
    const priceInjected = await actions['v2.commerce.catalog.editions.create'].handler(ctx(owner, { mediaId: 'media-1', title: 'Paper', description: 'Fine', mutationId: 'catalog-edition-price', expectedResourceVersion: null, priceMinor: 1 }) as never);
    expect(created.status).toBe(201); expect(created.data.content).toEqual({ id: 'edition-1', mediaId: 'media-1', title: 'Paper', description: 'Fine', status: 'draft', resourceVersion: '1' }); expect(created.data.content).not.toHaveProperty('currency'); expect(created.data.content).not.toHaveProperty('priceMinor');
    expect(durable.createEdition).toHaveBeenCalledWith(owner, expect.objectContaining({ currency: 'USD', priceMinor: 0 })); expect(currencyInjected.status).toBe(400); expect(priceInjected.status).toBe(400); expect(durable.createEdition).toHaveBeenCalledTimes(1);
  });
});
