import { Sequelize } from 'sequelize';
import initializeOperation, { TrailsTrustedPhotoshopIngestionOperationTable } from '../../src/db/mysql/models/trailsTrustedPhotoshopIngestionOperation';
import initializeArtifact, { TrailsTrustedPhotoshopIngestionArtifactTable } from '../../src/db/mysql/models/trailsTrustedPhotoshopIngestionArtifact';
import initializeFence, { TrailsTrustedPhotoshopStorageWriteFenceTable } from '../../src/db/mysql/models/trailsTrustedPhotoshopStorageWriteFence';
import { createSequelizeTrustedPhotoshopIngestionModels, MySqlTrustedPhotoshopIngestionOperationRepository } from '../../src/apps/trails/repository/mysqlTrustedPhotoshopIngestionOperation';
import { SequelizeTrailsSyncConnection } from '../../src/apps/trails/repository/mysqlPortfolioCategorySync';

const describeIntegration = process.env.TRAILS_MYSQL_INTEGRATION === '1' ? describe : describe.skip;
const artifacts = () => (['grid-960', 'cover-2048', 'preview-4096'] as const).flatMap(logicalRendition => (['avif', 'webp', 'jpeg'] as const).map(codec => ({ logicalRendition, codec, mimeType: `image/${codec}` as const, width: 960, height: 600, byteLength: 100, sha256: 'a'.repeat(64) })));

describeIntegration('trusted Photoshop ingestion operation MySQL schema', () => {
  let sequelize: Sequelize;
  let repository: MySqlTrustedPhotoshopIngestionOperationRepository;
  beforeAll(async () => { sequelize = new Sequelize('darwin_trails_it', 'darwin_trails_it', 'darwin_trails_it', { host: '127.0.0.1', port: 3308, dialect: 'mysql', logging: false }); await sequelize.authenticate(); const operations = initializeOperation(sequelize); const artifactModels = initializeArtifact(sequelize); const fenceModels = initializeFence(sequelize); await require('../../scripts/migrations').applyTrailsCategoryMigrations(sequelize); repository = new MySqlTrustedPhotoshopIngestionOperationRepository(new SequelizeTrailsSyncConnection(sequelize), createSequelizeTrustedPhotoshopIngestionModels(operations, artifactModels, fenceModels)); });
  afterAll(async () => { await sequelize.close(); });
  it('persists the private parent, exact 3x3 child identity, and ten internal write fences without public leakage', async () => { const created = await repository.create({ tenantId: 'mysql-ingestion-tenant', operationId: 'mysql-ingestion-operation', ownerUserId: 'mysql-ingestion-owner', assetId: 'mysql-ingestion-asset', assetFingerprint: 'b'.repeat(64), registerMutationId: 'mysql-register', artifactMutationId: 'mysql-artifacts', master: { mimeType: 'image/jpeg', byteLength: 200, sha256: 'c'.repeat(64) }, artifacts: artifacts() }); expect(created.artifacts).toHaveLength(9); expect(JSON.stringify(created)).not.toContain('objectIdentity'); expect(await TrailsTrustedPhotoshopIngestionOperationTable.count({ where: { tenantId: created.tenantId, operationId: created.operationId } })).toBe(1); expect(await TrailsTrustedPhotoshopIngestionArtifactTable.count({ where: { tenantId: created.tenantId, operationId: created.operationId } })).toBe(9); expect(await TrailsTrustedPhotoshopStorageWriteFenceTable.count({ where: { tenantId: created.tenantId, operationId: created.operationId } })).toBe(10); });
  it('persists a lease claim and CAS phase transition', async () => { const created = await repository.create({ tenantId: 'mysql-ingestion-tenant', operationId: 'mysql-ingestion-cas', ownerUserId: 'mysql-ingestion-owner', assetId: 'mysql-ingestion-asset-cas', assetFingerprint: 'd'.repeat(64), registerMutationId: 'mysql-register-cas', artifactMutationId: 'mysql-artifacts-cas', master: { mimeType: 'image/jpeg', byteLength: 200, sha256: 'e'.repeat(64) }, artifacts: artifacts() }); const claimed = await repository.claim({ tenantId: created.tenantId, operationId: created.operationId, owner: 'mysql-worker', leaseMs: 60_000 }); const pending = await repository.transition({ tenantId: created.tenantId, operationId: created.operationId, leaseOwner: 'mysql-worker', expectedVersion: claimed.resourceVersion, phase: 'storage_pending' }); expect(pending).toEqual(expect.objectContaining({ phase: 'storage_pending', resourceVersion: '3', lease: expect.objectContaining({ owner: 'mysql-worker' }) })); expect(await TrailsTrustedPhotoshopIngestionOperationTable.findOne({ where: { tenantId: created.tenantId, operationId: created.operationId, phase: 'storage_pending', resourceVersion: '3', leaseOwner: 'mysql-worker' } })).toBeDefined(); });
});
